import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const kraehenfuss: ContentEntry = {
  id: "weed_kraehenfuss",
  category: "WEED",
  name: "Niederliegender Krähenfuß",
  scientificName: "Lepidium coronopus",
  aliases: [
    "Krähenfuß-Schuppenkresse",
    "Gemeiner Krähenfuß",
    "Warzenkresse",
    "Coronopus squamatus",
  ],
  description:
    "Ein flach am Boden liegendes Kreuzblütler-Unkraut, das vor allem auf verdichteten, getretenen Böden wächst – also Rasen, Wege und Einfahrten. Im Rasen bildet es flache Rosetten, die der Mäher nicht erwischt; sie verdrängen die Gräser und hinterlassen kahle, unebene Stellen. Die Pflanze ist ein klassischer Zeiger für Bodenverdichtung.",
  traits: [
    "Flach niederliegende, dem Boden anliegende Rosetten",
    "Tief fiederteilige, frischgrüne Blätter (kresseartig)",
    "Winzige weiße Blüten in dichten Trauben (Juni–September)",
    "Höckerig-warzige, nierenförmige Früchtchen (namensgebender 'Krähenfuß')",
    "Kresse-/senfartiger Geruch beim Zerreiben",
    "Kräftige Pfahlwurzel",
  ],
  significance: "HARMFUL",
  defaultUrgency: "THIS_WEEK",
  habitat:
    "Verdichtete, getretene Böden – Rasen, Wege, Einfahrten, Toreinfahrten, Pflasterfugen. Bevorzugt nährstoffreiche, lehmige Böden mit gestörter Struktur.",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["LAWN", "GARDEN", "TERRACE"],
  confusionRisk: [
    {
      name: "Zweiknotiger Krähenfuß (Lepidium didymum)",
      note: "Sehr ähnlich, aber zarter und kleiner; Früchtchen zweiteilig und glatt statt warzig.",
    },
    {
      name: "Schafgarbe-Rosette (Achillea millefolium)",
      note: "Ebenfalls fein gefiederte Blätter, wächst aber aufrechter und riecht aromatisch-würzig, nicht nach Kresse.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
    notes:
      "Ungiftig. Junge Blätter sind essbar und schmecken scharf wie Kresse; historisch als Wildgemüse genutzt. Vor dem Verzehr sicher bestimmen.",
  },
  methods: [
    {
      id: "m_ausstechen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Mit Unkrautstecher ausstechen",
      description:
        "Die effektivste chemiefreie Soforthilfe im Rasen. Wichtig ist, die Pfahlwurzel komplett mitzunehmen – Wurzelreste treiben wieder aus.",
      steps: [
        "Boden vorab anfeuchten (nach Regen oder Gießen geht es leichter)",
        "Unkrautstecher senkrecht neben der Rosette einstechen",
        "Langsam kippen und die Pflanze mit ganzer Wurzel herausheben",
        "Vor der Samenreife arbeiten, um die Ausbreitung zu stoppen",
        "Entstandenes Loch mit Erde füllen und Rasen nachsäen",
      ],
      effort: "MEDIUM",
      durationMin: 5,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_boden_lockern",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Bodenverdichtung beseitigen – die eigentliche Ursache",
      description:
        "Der Krähenfuß ist ein Zeiger für verdichteten Boden. Lockert man die Struktur, verliert er seinen Standortvorteil und kommt deutlich seltener wieder.",
      steps: [
        "Betroffene Rasenflächen aerifizieren (Belüftungsgabel oder Aerifizierer)",
        "Stark getretene Stellen tief lockern und mit Sand einschlämmen",
        "Verdichtung künftig vermeiden – feste Wege anlegen, nicht quer über nasse Flächen laufen",
        "Auf Wegen/Einfahrten die Fugen offen halten und Material auflockern",
      ],
      effort: "MEDIUM",
      durationMin: 90,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_rasen_staerken",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Rasen nachsäen und stärken",
      description:
        "Weil der Krähenfuß flach unter der Mähhöhe wächst, verdrängt ihn nur ein dichter, kräftiger Rasen dauerhaft. Kombiniere das immer mit dem Ausstechen und der Bodenlockerung.",
      steps: [
        "Kahle Stellen nach dem Ausstechen sofort nachsäen",
        "Mit organischem Rasendünger versorgen (April, Juni, August)",
        "Schnitthöhe bei 4–5 cm halten – nicht zu kurz mähen",
        "Bei Trockenheit durchdringend wässern (1–2×/Woche)",
      ],
      effort: "MEDIUM",
      durationMin: 120,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_heisswasser",
      type: "HOME_REMEDY",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Heißwasser-Behandlung (nur auf befestigten Flächen)",
      description:
        "Kochendes Wasser direkt auf die Rosette – geeignet für Pflasterfugen, Wege und Einfahrten, NICHT im Rasen (es zerstört auch die Gräser).",
      steps: [
        "Wasserkocher aufheizen",
        "Heißes Wasser direkt auf die Rosette und den Wurzelhals gießen",
        "Nach 2–3 Tagen die abgestorbene Pflanze samt Wurzelrest entfernen",
        "Bei Bedarf wiederholen, bis kein Neuaustrieb mehr kommt",
      ],
      effort: "EASY",
      durationMin: 5,
      timeframe: "NOW",
      ecoScore: 4,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Kochendes Wasser (ca. 1 l pro Pflanze)"],
    },
  ],
  prevention: [
    "Bodenverdichtung vermeiden – das ist die wirksamste Vorbeugung gegen den Krähenfuß.",
    "Rasen regelmäßig aerifizieren, damit er dicht und konkurrenzstark bleibt.",
    "Kahle Rasenstellen sofort nachsäen, bevor der Krähenfuß den offenen Boden besiedelt.",
    "Vor der Samenreife (Sommer) entfernen – die warzigen Früchtchen verbreiten viele Samen.",
    "Pflasterfugen und Einfahrten regelmäßig säubern.",
  ],
  sources: [SOURCES.JKI, SOURCES.GPP],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/4/46/Coronopus_squamatus_eF.jpg",
};
