import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const loewenzahn: ContentEntry = {
  id: "weed_loewenzahn",
  category: "WEED",
  name: "Gewöhnlicher Löwenzahn",
  scientificName: "Taraxacum officinale",
  aliases: ["Pusteblume", "Kuhblume", "Maiblume"],
  description:
    "Der Löwenzahn ist eine der häufigsten Wildpflanzen in Deutschland. Im Rasen ein klassisches 'Unkraut', in Wildblumenwiesen ein wertvoller Bienenmagnet. Essbar in Blatt, Blüte und Wurzel.",
  traits: [
    "Gezähnte, rosettenförmige Grundblätter",
    "Hohler, milchsaftführender Stängel",
    "Leuchtend gelbe Korbblüten (März–Oktober)",
    "Weiße Pusteblume mit Flugschirmen",
    "Tief reichende Pfahlwurzel bis 30 cm",
  ],
  significance: "NUISANCE",
  defaultUrgency: "MONITOR",
  habitat: "Rasen, Wegränder, Beete, Wiesen – auf nährstoffreichen, offenen Böden",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "LAWN", "BED", "BALCONY"],
  confusionRisk: [
    {
      name: "Ferkelkraut (Hypochaeris radicata)",
      note: "Ähnliche gelbe Blüten, aber verzweigter Stängel und behaarte Blätter.",
    },
    {
      name: "Wiesen-Pippau (Crepis biennis)",
      note: "Höher wachsend, mehrere Blüten pro Stängel.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
    notes:
      "Milchsaft kann empfindliche Haut leicht reizen. Blätter und Blüten sind essbar und werden für Salate, Tee und Sirup verwendet.",
  },
  methods: [
    {
      id: "m_stechen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Mit Unkrautstecher ausstechen",
      description:
        "Die effektivste chemiefreie Methode. Entscheidend: die gesamte Pfahlwurzel mitnehmen – Rückstände treiben wieder aus.",
      steps: [
        "Boden vorab anfeuchten (nach Regen oder Gießen)",
        "Unkrautstecher senkrecht neben der Rosette einstechen",
        "Langsam kippen und Pflanze mit kompletter Wurzel herausheben",
        "Entstandenes Loch mit Erde füllen, Rasen nachsäen",
        "Vor der Samenbildung arbeiten, um Ausbreitung zu stoppen",
      ],
      effort: "MEDIUM",
      durationMin: 5,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_rasenpflege",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Rasen stärken – dichter Wuchs verdrängt Löwenzahn",
      description:
        "Dichter, gesunder Rasen bietet Löwenzahn keinen Platz. Langfristig die wichtigste Maßnahme.",
      steps: [
        "Im Frühjahr vertikutieren und nachsäen",
        "Regelmäßig mit organischem Rasendünger versorgen (April, Juni, August)",
        "Schnitthöhe bei 4–5 cm halten – nicht zu kurz mähen",
        "Bei Trockenheit durchdringend wässern (1–2×/Woche)",
      ],
      effort: "MEDIUM",
      durationMin: 120,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_bienenecke",
      type: "CULTURAL",
      style: ["ORGANIC"],
      title: "Bienenweide statt Bekämpfung",
      description:
        "Löwenzahn ist eine der wichtigsten Frühjahrsnahrungen für Wildbienen. Statt zu bekämpfen: eine ungemähte Ecke als bewusste Bienenweide widmen.",
      steps: [
        "1–2 m² Randfläche als Wildblumenecke ausweisen",
        "Dort nur 1× im Jahr mähen (August nach Samenreife)",
        "Ergänzen mit Wildblumen-Saatmischung 'bienenfreundlich'",
      ],
      effort: "EASY",
      durationMin: 30,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_essig_salz",
      type: "HOME_REMEDY",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Heißwasser-Behandlung (nur auf befestigten Flächen)",
      description:
        "Kochendes Wasser direkt auf die Rosette. Auf befestigten Flächen wie Wegen, NICHT im Rasen (zerstört auch die Gräser).",
      steps: [
        "Wasserkocher aufheizen",
        "Heißes Wasser direkt auf die Rosette und den Austritt aus dem Pflaster gießen",
        "Nach 2–3 Tagen abgestorbene Pflanze entfernen",
      ],
      effort: "EASY",
      durationMin: 5,
      timeframe: "NOW",
      ecoScore: 4,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Kochendes Wasser (ca. 1 l pro Pflanze)"],
    },
  ],
  prevention: [
    "Rasenlücken sofort nachsäen – Löwenzahn besiedelt offenen Boden blitzschnell.",
    "Vor der Samenbildung (April/Mai) aktiv werden, pro Pflanze tausende Flugsamen.",
    "Kompost nur aus gut durchhitztem Material – Wurzelstücke überleben sonst.",
    "Pflasterfugen regelmäßig säubern, bevor sich Löwenzahn festsetzt.",
  ],
  sources: [SOURCES.JKI, SOURCES.GPP, SOURCES.NABU],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/4/4f/DandelionFlower.jpg",
};
