import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const rose: ContentEntry = {
  id: "plant_rose",
  category: "PLANT",
  name: "Gartenrose",
  scientificName: "Rosa hybrida",
  aliases: ["Edelrose", "Teehybride"],
  description:
    "Die 'Königin der Blumen' – Klassiker in deutschen Gärten. Über 30.000 Sorten weltweit. Pflegeintensiver als Wildrosen, dafür oft dauerblühend. Anfällig für Pilzkrankheiten (Sternrußtau, Mehltau, Rost) und Blattläuse – aber bei guter Pflege viele Jahre haltbar.",
  traits: [
    "Stacheliger Strauch, 40 cm bis 3 m je nach Sorte",
    "Gefiederte Blätter, meist 5 Fiederblättchen",
    "Einzeln oder in Dolden stehende Blüten",
    "Blütenfarben: weiß, gelb, orange, rot, rosa, violett – fast alles außer echtes Blau",
    "Stachel (korrekt: keine 'Dornen') am Stängel",
  ],
  significance: "BENEFIT",
  defaultUrgency: "GONE",
  habitat: "Sonnig (6+ Std.), luftig, tiefgründiger lehmiger Boden",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED", "POTS"],
  confusionRisk: [
    {
      name: "Hagebutte / Wildrose (Rosa canina)",
      note: "Einfache Blüten, weniger Sorten, robuster, Früchte als Hagebutten essbar.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
    notes:
      "Stacheln können Verletzungen verursachen – für Kinderhände vorsichtig. Hagebutten (Früchte) sind essbar und vitamin-C-reich.",
  },
  methods: [
    {
      id: "m_fruehjahr_schnitt",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Frühjahrsrückschnitt (Forsythienblüte)",
      description:
        "Wenn die Forsythie gelb blüht, ist Rosenschnitt-Zeit. Richtiger Schnitt = starke Blüte.",
      steps: [
        "Alle abgestorbenen und kranken Triebe bodennah entfernen",
        "Edelrosen stark zurückschneiden: auf 3–5 kräftige Augen (ca. 20 cm)",
        "Strauchrosen moderat: ein Drittel einkürzen, alte Triebe auslichten",
        "Schnitt immer über einem nach außen zeigenden Auge",
        "Schräger Schnitt (45°) verhindert, dass Regen ins Auge läuft",
        "Schneidwerkzeug vor und nach Arbeit desinfizieren",
      ],
      effort: "MEDIUM",
      durationMin: 30,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_duengung",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Organische Düngung – 3× pro Saison",
      description:
        "Rosen sind Starkzehrer. Organischer Dünger versorgt langsam und schont das Bodenleben.",
      steps: [
        "Ende März/Anfang April: Rosendünger nach Herstellerangabe ins Wurzelbereich einarbeiten",
        "Mitte/Ende Juni nach der ersten Blüte: zweite Gabe",
        "Ende Juli: letzte Gabe (später nicht mehr – Pflanze muss aushärten)",
        "Hornspäne als Grundversorgung beim Pflanzen einarbeiten",
        "Kompost als Mulchauflage 2–3 cm dick",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_pilzvorbeugung",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Pilzkrankheiten vorbeugen",
      description:
        "Rosen sind pilzanfällig. Prävention ist günstiger und wirkungsvoller als Behandlung.",
      steps: [
        "Nur am Boden gießen, niemals über die Blätter",
        "Morgens gießen, damit der Boden tagsüber abtrocknet",
        "Falllaub im Herbst komplett entfernen",
        "Bei Neupflanzung ADR-zertifizierte Sorten wählen (Pilz-getestet)",
        "Ausreichenden Pflanzabstand wahren (mind. 50 cm)",
      ],
      effort: "EASY",
      durationMin: 20,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
  ],
  prevention: [
    "Bei Neukauf: ADR-Label (Allgemeine Deutsche Rosenneuheitenprüfung) = pilzresistent.",
    "Niemals Rosen auf Standorte pflanzen, wo zuvor Rosen standen (Boden-Müdigkeit).",
    "Bodenverbesserung vor Pflanzung: 50 l Kompost pro Pflanze einarbeiten.",
    "Knoblauch oder Lavendel als Nachbarn wirkt vorbeugend gegen Schädlinge.",
  ],
  sources: [SOURCES.GPP],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/4/47/Rosa_%27Mme_Caroline_Testout%27.jpg",
};
