import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const tomate: ContentEntry = {
  id: "plant_tomate",
  category: "PLANT",
  name: "Tomate",
  scientificName: "Solanum lycopersicum",
  aliases: ["Paradeiser", "Paradiesapfel", "Liebesapfel"],
  description:
    "Deutschlands beliebteste Gartenpflanze. Nachtschattengewächs aus Südamerika. Braucht Wärme, Sonne und windgeschützten Stand. Wichtigste Herausforderungen: Kraut- und Braunfäule, Blütenendfäule, richtiger Rückschnitt. Bei guter Pflege 2–5 kg Ertrag pro Pflanze.",
  traits: [
    "Meist 1–2 m hohe Stab- oder Buschform",
    "Fiederblätter mit charakteristischem Duft",
    "Gelbe Blüten in Rispen",
    "Früchte rund, oval, herzförmig – rot, gelb, orange, grün, violett",
    "Klebrige Drüsenhaare an Stängel und Blättern",
  ],
  significance: "BENEFIT",
  defaultUrgency: "GONE",
  habitat: "Warm, sonnig, windgeschützt, am besten überdacht (Freiland mit Regenschutz)",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED", "BALCONY", "TERRACE", "POTS"],
  confusionRisk: [
    {
      name: "Physalis / Andenbeere",
      note: "Verwandte Pflanze, aber Früchte in papierartiger Hülle.",
    },
    {
      name: "Kartoffel",
      note: "Gleiche Familie (Nachtschattengewächs), oberirdische Teile GIFTIG. Fruchtfolge wichtig.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: ["DOG", "CAT"],
    allergyRisk: false,
    invasive: false,
    notes:
      "Reife rote Früchte unbedenklich. GRÜNE Früchte, Blätter und Stängel enthalten Solanin – nicht roh verzehren. Haustiere sollten Pflanzenteile nicht fressen.",
  },
  methods: [
    {
      id: "m_auspflanzung",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Auspflanzen nach den Eisheiligen",
      description:
        "Die goldene Regel: erst nach dem 15. Mai raus, außer bei überdachten/geschützten Standorten. Tomaten vertragen keinen Frost.",
      steps: [
        "Jungpflanzen 10 Tage vor Auspflanzung abhärten (tagsüber raus, nachts rein)",
        "Pflanzloch großzügig (40×40×40 cm) mit Kompost vorbereiten",
        "Stab oder Spirale VOR dem Pflanzen setzen – beschädigt sonst Wurzeln",
        "Pflanze bis zum ersten echten Blatt tief einsetzen – es bilden sich zusätzliche Wurzeln am Stängel",
        "Gründlich angießen",
      ],
      effort: "MEDIUM",
      durationMin: 30,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_ausgeizen",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Ausgeizen – Seitentriebe entfernen",
      description:
        "Bei Stabtomaten absolut notwendig: Seitentriebe in Blattachseln zwingen die Pflanze, ihre Energie in Früchte statt Blätter zu stecken.",
      steps: [
        "Alle Seitentriebe in Blattachseln ausbrechen (mit Fingern, nicht schneiden)",
        "Morgens arbeiten – Wunden trocknen schneller",
        "Wöchentlich wiederholen während der Wachstumsphase",
        "Buschtomaten NICHT ausgeizen – sind fürs Wuchern gezüchtet",
        "Ende August Triebspitze kappen, damit letzte Früchte reifen",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_giessen",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Gleichmäßig gießen – Platzen verhindern",
      description:
        "Tomaten hassen Schwankungen. Wenn nach trockenen Tagen plötzlich viel Regen oder Gießen kommt, platzen Früchte. Lösung: konstant gießen.",
      steps: [
        "Alle 2–3 Tage durchdringend am Stamm gießen (2–4 l pro Pflanze)",
        "Niemals über Blätter gießen – Pilzrisiko",
        "Mulchen mit Stroh oder Grasschnitt hält Feuchtigkeit und wärmt Boden",
        "Tropfschläuche oder Tomatentopf mit Wasserreservoir ideal",
        "Bei Hitze morgens und abends kontrollieren",
      ],
      effort: "EASY",
      durationMin: 10,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_regendach",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Überdachung – gegen Kraut- und Braunfäule",
      description:
        "Der mit Abstand größte Ertrags-Booster und Krankheits-Stopper. Nasse Blätter = Phytophthora-Infektion = Totalausfall möglich.",
      steps: [
        "Tomatenhaus, Folientunnel oder einfaches Vordach über Freilandtomaten",
        "Seitlich offen für Luftzirkulation",
        "Höhe mind. 2 m, damit Pflanzen ausreichend Platz haben",
        "Regenwasser ableiten",
      ],
      effort: "HARD",
      durationMin: 180,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€€",
    },
  ],
  prevention: [
    "Fruchtfolge beachten: 3–4 Jahre keine Nachtschattengewächse (Tomate, Kartoffel, Paprika) auf gleicher Fläche.",
    "Bei Neupflanzung phytophthora-tolerante Sorten wählen ('Phantasia F1', 'De Berao').",
    "Blütenendfäule = Kalziummangel: Mit Algenkalk oder Steinmehl in der Jugend vorbeugen.",
    "Pflanzabstand 60 cm für Luftzirkulation.",
    "Nie neben Kartoffeln pflanzen (gleiche Krankheiten).",
  ],
  sources: [SOURCES.JKI, SOURCES.GPP, SOURCES.LFL],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/f/f3/Tomatoes-on-the-bush.jpg",
};
