import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const florfliege: ContentEntry = {
  id: "beneficial_florfliege",
  category: "BENEFICIAL",
  name: "Florfliege",
  scientificName: "Chrysoperla carnea",
  aliases: ["Goldauge", "Stinkfliege"],
  description:
    "Die Larven der Florfliege – volkstümlich 'Blattlauslöwen' genannt – fressen während ihrer Entwicklung 200–500 Blattläuse pro Stück und gehören damit zu den effektivsten Nützlingen im Garten. Die zierliche Imago ist goldgrün gefärbt, mit langen Antennen und transparenten, dicht geäderten Flügeln. Erwachsene Florfliegen überwintern häufig in Häusern, Schuppen oder Insektenhotels; bei Stress geben sie einen leicht unangenehmen Geruch ab – daher der unverdienten Beinamen 'Stinkfliege'.",
  traits: [
    "Imago: ~15 mm, zartgrün mit goldglänzenden Netzflügeln und langen Antennen",
    "Larven: gelblich-braun, spindelförmig, mit kräftigen Greifzangen – der 'Blattlauslöwe'",
    "Eier: einzeln auf langen, haarfeinen Stielen an Blättern, nahe Blattlauskolonien",
    "Überwinterung als Imago, oft in trockenen, geschützten Hohlräumen",
  ],
  significance: "BENEFIT",
  defaultUrgency: "MONITOR",
  habitat:
    "Gärten mit blütenreichem Saum, Stauden und Wildecken; Larven bevorzugt an Blattlaus-Befallsstellen auf Rosen, Gemüse und Sträuchern",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED", "BALCONY", "POTS"],
  confusionRisk: [
    {
      name: "Marienkäferlarven",
      note: "Schwarz-orange, gepanzert und dunkler – ähnlich aktiv an Blattlauskolonien, aber klar zu unterscheiden durch Körperform.",
    },
    {
      name: "Schwebfliegenlarven",
      note: "Madenartig, beinlos, gelblich – ebenfalls Blattlausjäger, aber ohne die charakteristischen Greifzangen der Florfliegenlarve.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
    notes:
      "Vollständig ungefährlich. Der leichte Geruch bei Bedrohung ist harmlos und nur kurzzeitig wahrnehmbar.",
  },
  methods: [
    {
      id: "m_florfliege_hotel",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Florfliegenkasten oder Insektenhotel aufhängen",
      description:
        "Spezielle Florfliegenkästen (aus dem Fachhandel oder selbst gebaut) bieten ideale Überwinterungsquartiere und fördern stabile Populationen über Jahre.",
      steps: [
        "Florfliegenkasten oder Insektenhotel mit Holzwolle, Kiefernzapfen oder Stroh befüllen",
        "Halbschattigen, witterungsgeschützten Standort wählen – Nordost- oder Ostausrichtung",
        "Im September/Oktober aufhängen, bevor erste Fröste kommen",
        "Füllung jährlich im Frühjahr erneuern",
      ],
      effort: "EASY",
      durationMin: 30,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_florfliege_dolden",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Blütenreiches Saumbiotop mit Doldenblütlern anlegen",
      description:
        "Erwachsene Florfliegen ernähren sich von Nektar und Pollen. Doldenblütler, Schafgarbe und Fenchel locken sie gezielt an und sichern die Reproduktion im Garten.",
      steps: [
        "Dill, Fenchel, Schafgarbe, Wilde Möhre und Koriander einstreuen",
        "Mindestens einen ungepflegten Saumstreifen von 0,5–1 m Breite anlegen",
        "Verschiedene Blühzeiträume kombinieren (April–Oktober)",
        "Keine Kürz-Schnitte im Hochsommer – Blüten stehen lassen",
      ],
      effort: "EASY",
      durationMin: 60,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_florfliege_insektizidverzicht",
      type: "CULTURAL",
      style: ["ORGANIC"],
      title: "Auf Breitband-Insektizide verzichten",
      description:
        "Selbst 'sanfte' Mittel wie Pyrethrum töten Florfliegenlarven und -eier zuverlässig ab. Der Verzicht ist die wichtigste Einzelmaßnahme für eine stabile Population.",
      steps: [
        "Keine Breitband-Insektizide ausbringen, auch nicht auf Basis von Pyrethrum oder Neem",
        "Bei Blattlausbefall zunächst 3–5 Tage abwarten – Florfliegenlarven sind oft schon unterwegs",
        "Falls nötig: gezieltes Abspritzen mit Wasser oder punktuelles Behandeln",
      ],
      effort: "EASY",
      durationMin: 0,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_florfliege_aussetzen",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "EFFECTIVE"],
      title: "Florfliegeneier oder -larven bei akutem Blattlausbefall aussetzen",
      description:
        "Im Fachhandel und über Nützlingsproduzenten sind Florfliegeneier auf Trägermaterial erhältlich. Bei starkem Blattlausbefall eine schnell wirksame Ergänzung.",
      steps: [
        "Florfliegeneier (auf Klebeband oder Karton) direkt an befallene Pflanzen hängen",
        "Bei Larven: auf Befallsstellen setzen, nicht anfassen – Pinsel verwenden",
        "Temperatur sollte über 15 °C liegen für gute Schlupfrate",
        "Nicht gleichzeitig Kontaktinsektizide einsetzen",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_florfliege_totholz",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Überwinterungsquartiere im Garten belassen",
      description:
        "Natürliche Strukturen – Totholzhaufen, hohle Stängel, altes Laub – sind natürliche Winterquartiere für Florfliegen und viele andere Nützlinge.",
      steps: [
        "Alte Staudenstängel erst im März/April zurückschneiden, nicht im Herbst",
        "Totholzecke aus gestapelten Ästen und Rindenstücken anlegen",
        "Herbstlaub unter Sträuchern liegen lassen",
        "Trockene Ecken in Schuppen und Kellern ungestört lassen (überwinternde Imagines!)",
      ],
      effort: "EASY",
      durationMin: 30,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
  ],
  prevention: [
    "Lebensraum dauerhaft anbieten: Saumbiotope, Doldenblütler und Totholzstrukturen sorgen für stabile Populationen ohne Eingriff.",
    "Nicht im Herbst 'aufräumen' – viele Florfliegen überwintern in Staudenresten und Laub.",
    "Florfliegen im Haus nicht töten – sie suchen nur Winterquartier und verschwinden im Frühjahr von selbst.",
  ],
  sources: [SOURCES.NABU, SOURCES.JKI],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/4/4e/Chrysoperla_carnea_October_2007_Wakehurst_2.jpg",
};
