import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const schwebfliege: ContentEntry = {
  id: "beneficial_schwebfliege",
  category: "BENEFICIAL",
  name: "Schwebfliege",
  scientificName: "Syrphidae",
  aliases: ["Schwirrfliege"],
  description:
    "Schwebfliegen haben einen bemerkenswerten Doppelnutzen: Die Imagines sind nach Honigbienen und Hummeln die wichtigsten Bestäuber in Mitteleuropa, während die Larven vieler Arten bis zu 1.000 Blattläuse pro Monat fressen. Die auffällige gelb-schwarze Streifenzeichnung ist Wespen-Mimikry zum Schutz vor Vögeln – tatsächlich haben Schwebfliegen keinen Stachel und stechen nie. Erkennungsmerkmal: das charakteristische stationäre Schweben auf der Stelle, wie ein kleiner Helikopter.",
  traits: [
    "Wespen-Mimikry: gelb-schwarze Querstreifen, aber nur 2 Flügel (Wespen haben 4)",
    "Schwebt bewegungslos in der Luft ('Helikopter-Manöver'), dann blitzschneller Richtungswechsel",
    "Kurze, borstige Antennen – deutlich kürzer als bei Wespen oder Bienen",
    "Larven: beinlos, madenartig, gelblich – in Blattlauskolonien zu finden",
    "Körperlänge je nach Art 5–15 mm",
  ],
  significance: "BENEFIT",
  defaultUrgency: "MONITOR",
  habitat:
    "Gärten mit Wildblumen und Doldenblütlern, ungespritzte Saumbereiche, Obstwiesen; Larven direkt an Blattlaus-befallenen Trieben auf Rosen, Gemüse und Gehölzen",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED", "BALCONY", "POTS"],
  confusionRisk: [
    {
      name: "Wespen (Vespidae)",
      note: "Wichtigstes Unterscheidungsmerkmal: Wespen haben 4 Flügel, fliegen direkter und sitzen auf Süßem oder Fleisch. Schwebfliegen schweben auf der Stelle – das können Wespen nicht.",
    },
    {
      name: "Honigbienen und Hummeln",
      note: "Bienen sind behaart und fliegen gleichmäßiger. Schwebfliegen sind kaum behaart, haben kürzere Antennen und das typische Schwebeverhalten.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
    notes:
      "Völlig harmlos – kein Stachel, keine Abwehrstoffe. Trotz Wespen-Mimikry stellt die Schwebfliege keinerlei Gefahr dar.",
  },
  methods: [
    {
      id: "m_schwebfliege_dolden",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Doldenblütler als Nektarquelle pflanzen",
      description:
        "Schwebfliegen bevorzugen flach geöffnete Blüten, die ihren kurzen Rüssel nicht überfordern. Doldenblütler sind ideal und ziehen ein breites Artenspektrum an.",
      steps: [
        "Dill, Fenchel, Wilde Möhre, Schafgarbe und Bärenklau im Garten einplanen",
        "Liebstöckel und Koriander blühen lassen statt abzuernten",
        "Direkt neben Beete pflanzen – kurze Wege zur Blattlauspopulation begünstigen Eiablage",
        "Verschiedene Höhenstufen kombinieren: Bodendecker, Stauden, Sträucher",
      ],
      effort: "EASY",
      durationMin: 60,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_schwebfliege_wildblumen",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Wildblumeninseln mit langer Blühperiode anlegen",
      description:
        "Eine artenreiche Blühfläche von selbst 1–2 m² reicht aus, um Schwebfliegen dauerhaft in den Garten zu locken und die Larvenentwicklung zu fördern.",
      steps: [
        "Wildblumen-Saatmischung 'Insektenweide' oder 'Bienen & Hummeln' aussäen",
        "Saum entlang Zaun oder Kompost anlegen – mindestens 0,5 m breit",
        "Frühjahrsblüher (Gänseblümchen, Vergissmeinnicht) bis Herbstblüher (Aster, Tagetes) kombinieren",
        "Abgestorbene Stängel im Winter stehen lassen – Überwinterungsort für Insekten",
      ],
      effort: "EASY",
      durationMin: 90,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_schwebfliege_insektizidverzicht",
      type: "CULTURAL",
      style: ["ORGANIC"],
      title: "Auf Insektizide verzichten",
      description:
        "Schwebfliegenlarven sind gegen Kontaktinsektizide ebenso empfindlich wie andere Nützlinge. Kein Insektizid unterscheidet zwischen Schädling und Nützling.",
      steps: [
        "Keine Spritzungen mit Insektiziden, Pyrethrum, Neem oder Seifenlösungen an blühenden Pflanzen",
        "Bei Blattlausbefall zunächst 3–5 Tage warten – Schwebfliegenlarven entwickeln sich oft parallel",
        "Falls Eingriff nötig: mechanisch (abspritzen) statt chemisch",
      ],
      effort: "EASY",
      durationMin: 0,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_schwebfliege_strukturen",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Steinhaufen und Holzstapel als Versteck anlegen",
      description:
        "Schwebfliegen benötigen Strukturen zum Schutz und zur Überwinterung. Trockene, windgeschützte Ecken erhöhen die Überlebensrate und die Rückkehr im Frühjahr.",
      steps: [
        "Steinhaufen oder Trockenmauer in einer warmen, sonnigen Ecke anlegen",
        "Holzstapel aus ungesprittem Totholz aufschichten – mindestens 30 cm hoch",
        "Nicht zu sehr 'aufräumen': offene Bodenstellen und Mulch ergänzen das Angebot",
        "Mähroboter-freie Zonen im Saum lassen",
      ],
      effort: "EASY",
      durationMin: 45,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_schwebfliege_aufklaerung",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Schwebfliegen sicher erkennen – aufklären statt verscheuchen",
      description:
        "Viele Menschen verscheuchen oder töten Schwebfliegen aus Angst vor Wespen. Wer den Unterschied kennt, schützt einen wertvollen Nützling und Bestäuber.",
      steps: [
        "Beobachten: Schwebt das Tier bewegungslos in der Luft? → Schwebfliege, keine Wespe",
        "Flügelzahl zählen: 2 Flügel = Fliege, 4 Flügel = Wespe oder Biene",
        "Antennen prüfen: kurze, borsteartige Antennen → Schwebfliege",
        "Kinder aktiv einbeziehen: 'Rette die Schwebfliege'-Spiel beim Gärtnern",
        "Im Zweifel: einfach stehen lassen – sie sticht nicht",
      ],
      effort: "EASY",
      durationMin: 5,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
  ],
  prevention: [
    "Lebensraum erhalten: Saumbiotope, Wildblumenstreifen und Totholzstrukturen sichern stabile Populationen ohne weiteren Aufwand.",
    "Insektenvielfalt fördern: Je artenreicher der Garten, desto effektiver die natürliche Schädlingsregulierung – Schwebfliegen sind dabei ein Schlüsselelement.",
    "Nicht erschrecken: Die Wespen-Mimikry ist täuschend echt, aber Schwebfliegen sind harmlos. Aufklärung in der Familie verhindert unnötiges Töten.",
  ],
  sources: [SOURCES.NABU, SOURCES.JKI],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/e/e0/Syrphus_ribesii_m_aka.jpg",
};
