import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const blattlaeuse: ContentEntry = {
  id: "pest_blattlaeuse",
  category: "PEST",
  name: "Blattläuse",
  scientificName: "Aphidoidea",
  aliases: ["Grüne Läuse", "Pflanzenläuse"],
  description:
    "Die häufigsten Pflanzenschädlinge im Hausgarten. Saugen Pflanzensaft, scheiden Honigtau aus (klebt und fördert Rußtau), vermehren sich explosionsartig. Bei frühem Eingreifen und natürlichen Feinden meist gut zu kontrollieren.",
  traits: [
    "1–3 mm lang, grün, schwarz, rosa oder gelblich",
    "Dichte Kolonien an jungen Trieben und Knospen",
    "Geflügelte und ungeflügelte Formen",
    "Klebriger Honigtau auf Blättern und darunterliegenden Flächen",
    "Oft begleitet von Ameisen, die die Läuse 'melken'",
  ],
  significance: "HARMFUL",
  defaultUrgency: "IMMEDIATE",
  habitat:
    "An fast allen Nutz- und Zierpflanzen, bevorzugt junge Triebe und Blattunterseiten",
  seasons: ["SPRING", "SUMMER"],
  areas: ["GARDEN", "BED", "BALCONY", "TERRACE", "POTS"],
  confusionRisk: [
    {
      name: "Weiße Fliege (Trialeurodes vaporariorum)",
      note: "Ähnliches Schadbild (Saugen, Honigtau), aber kleine weiße 'Fliegen' statt grüne Kolonien.",
    },
    {
      name: "Thripse",
      note: "Winzige, längliche Insekten, verursachen silbrige Sprenkel auf Blättern.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_wasserstrahl",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Mit Wasserstrahl abspritzen",
      description:
        "Schnelle, effektive Erste-Hilfe-Maßnahme. Entfernt 60–80% der Läuse sofort, ohne Nützlinge zu schaden.",
      steps: [
        "Gartenschlauch auf mittleren bis starken Strahl einstellen",
        "Alle befallenen Triebe gründlich von allen Seiten abspritzen",
        "Besonders Blattunterseiten und Triebspitzen behandeln",
        "Morgens durchführen, damit Pflanze bis abends abtrocknen kann",
        "Bei Bedarf nach 3 Tagen wiederholen",
      ],
      effort: "EASY",
      durationMin: 10,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_schmierseife",
      type: "HOME_REMEDY",
      style: ["ORGANIC", "BALANCED"],
      title: "Schmierseifenlösung",
      description:
        "Bewährtes Hausmittel. Die Seife verstopft die Atemöffnungen der Läuse. Gut für den ersten Bekämpfungs-Durchgang.",
      steps: [
        "1 EL Kali-Schmierseife in 1 l warmes Wasser auflösen",
        "Optional: 1 EL Spiritus zusetzen (verstärkt die Wirkung)",
        "Abkühlen lassen und in Sprühflasche füllen",
        "Abends oder an bedecktem Tag auf befallene Stellen sprühen",
        "Alle 3–4 Tage wiederholen, bis Befall weg ist",
        "Nicht bei direkter Sonne spritzen – Verbrennungsgefahr an Blättern",
      ],
      effort: "EASY",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Kali-Schmierseife 1 EL", "Wasser 1 l", "Spiritus 1 EL (optional)"],
    },
    {
      id: "m_marienkaefer",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Nützlinge fördern oder ansiedeln",
      description:
        "Marienkäfer, Florfliegen, Schlupfwespen und Schwebfliegen sind natürliche Feinde. Eine einzige Marienkäfer-Larve frisst bis zu 400 Blattläuse.",
      steps: [
        "Insektizide dauerhaft vermeiden – tötet Nützlinge mit",
        "Blühende Kräuter pflanzen: Dill, Fenchel, Ringelblume, Kornblume",
        "Insektenhotel in der Nähe aufstellen",
        "Bei akutem Befall: Marienkäferlarven im Fachhandel oder online bestellen und gezielt aussetzen (10–30 € je nach Menge)",
      ],
      effort: "MEDIUM",
      durationMin: 60,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_neemöl",
      type: "ORGANIC_PRODUCT",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Neemöl-Präparat (Bio-Fungizid & Insektizid)",
      description:
        "Aus der Neem-Pflanze gewonnen, wirkt systemisch gegen saugende Insekten. Im Fachhandel als zugelassenes Pflanzenschutzmittel erhältlich.",
      steps: [
        "Zugelassenes Neem-Produkt nach Herstellerangabe mischen",
        "Abends auf befallene Pflanzenteile sprühen",
        "Nach 7 Tagen Wiederholungsbehandlung",
        "Vor Regen anwenden – 4 Stunden Einwirkzeit nötig",
        "Wartezeit bei Nutzpflanzen beachten (im Beipackzettel)",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "THIS_WEEK",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€€",
    },
  ],
  prevention: [
    "Pflanzen nicht mit Stickstoff überdüngen – weiche, saftreiche Triebe sind Blattlausmagnete.",
    "Mischkultur: Lavendel, Bohnenkraut, Kapuzinerkresse halten Blattläuse fern.",
    "Im Frühjahr Triebspitzen regelmäßig inspizieren – früh erkennen = leicht bekämpfen.",
    "Ameisenstraßen unterbrechen – Ameisen schützen und verteilen Blattläuse aktiv.",
    "Gesunde Pflanzen sind weniger anfällig: ausgewogene Düngung, richtiger Standort, genug Wasser.",
  ],
  sources: [SOURCES.JKI, SOURCES.GPP, SOURCES.LFL],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/1/19/Soybeanaphid.jpg",
};
