import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const buchsbaumzuensler: ContentEntry = {
  id: "pest_buchsbaumzuensler",
  category: "PEST",
  name: "Buchsbaumzünsler-Raupen",
  scientificName: "Cydalima perspectalis",
  aliases: ["Buchsbaummotte", "Buchsbaumzünsler"],
  description:
    "Aus Ostasien eingeschleppter Schmetterling, dessen Raupen Buchsbäume innerhalb weniger Wochen vollständig kahl fressen können. Weißliche Gespinste im Strauchinneren und schwarze Kotkrümel sind das erste Warnsignal. Bis zu drei Generationen pro Jahr – schnelles Handeln ist entscheidend.",
  traits: [
    "Raupen bis 4 cm lang, hellgrün mit schwarzen Längsstreifen und weißen Punkten",
    "Weißliche, dichte Gespinste im Inneren des Buchsbuschs",
    "Schwarze Kotkrümel zwischen den Trieben (typisches Erkennungszeichen)",
    "Skelettierter Fraß: Raupen fressen zuerst die Blattinnenfläche, dann alles",
    "Falter weiß mit braunem Rand, fliegt April–Oktober, mehrere Generationen",
  ],
  significance: "HARMFUL",
  defaultUrgency: "IMMEDIATE",
  habitat:
    "Ausschließlich an Buchsbaum (Buxus sempervirens und andere Buxus-Arten); bevorzugt dichte, schlecht belüftete Büsche",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED"],
  confusionRisk: [
    {
      name: "Buchsbaum-Blattfloh (Psylla buxi)",
      note: "Blattfloh verursacht Blattränder-Einrollung ohne Gespinst. Keine Raupen, kein Skelettierungsfraß.",
    },
    {
      name: "Frostschaden oder Trockenheitsschäden",
      note: "Gleichmäßig brauner Buchsbaum ohne Gespinste und Kotkrümel deutet auf abiotischen Stress hin, nicht auf Zünsler.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: true,
    notes:
      "Eingeschleppte invasive Art; befallene Pflanzenteile im Restmüll entsorgen, nicht kompostieren.",
  },
  methods: [
    {
      id: "m_buchszuensler_abklauben",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Raupen abklauben und Gespinste entfernen",
      description:
        "Bei leichtem Befall wirksam und ohne Chemie. Gespinste öffnen legt Raupen frei, die dann einzeln entfernt werden können.",
      steps: [
        "Gummihandschuhe anziehen – Buchsbaum kann Kontaktallergie auslösen",
        "Gespinste mit Finger oder Pinsel öffnen und auseinanderzupfen",
        "Sichtbare Raupen abklauben und in ein Gefäß mit Wasser oder Seifenwasser werfen",
        "Befallene Triebe mit Kotkrümeln abschneiden und im Restmüll entsorgen (nicht kompostieren!)",
        "Nach 7–10 Tagen wiederholen, da neue Raupen schlüpfen können",
      ],
      effort: "HARD",
      durationMin: 45,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_buchszuensler_abspritzen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Hochdruckstrahl zum Ausschwemmen der Raupen",
      description:
        "Hoher Wasserdruck spült Raupen aus dem dichten Gespinst heraus und erleichtert die anschließende Entsorgung.",
      steps: [
        "Plane oder Folie unter den Strauch legen",
        "Starken Wasserstrahl gezielt ins Strauchinnere richten",
        "Herausgespülte Raupen von der Folie aufsammeln und im Restmüll entsorgen",
        "Anschließend Gespinste manuell entfernen",
        "Bei starkem Befall mit Bacillus thuringiensis nachbehandeln",
      ],
      effort: "MEDIUM",
      durationMin: 20,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_buchszuensler_btk",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "EFFECTIVE"],
      title: "Bacillus thuringiensis var. kurstaki (B.t.k.) spritzen",
      description:
        "Das Bakterienpräparat B.t.k. ist bei jungen Raupen (1.–3. Stadium) hocheffektiv und dabei bienensicher und harmlos für Nützlinge. Wirkstoff muss von Raupe gefressen werden.",
      steps: [
        "Produkt mit B.t.k. im Gartenfachhandel kaufen (z. B. XenTari, Dipel)",
        "Nach Herstellerangabe in Wasser auflösen",
        "Abends spritzen – B.t.k. wird durch UV-Licht abgebaut",
        "Strauchinneres vollständig benetzen, wo Raupen fressen",
        "Nach 5–7 Tagen wiederholen – Wirkung tritt nach 2–4 Tagen ein",
        "Nur bei Temperaturen über 10 °C wirksam",
      ],
      effort: "MEDIUM",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_buchszuensler_pheromonfalle",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Pheromonfallen zum Falter-Monitoring",
      description:
        "Pheromonfallen fangen männliche Falter und zeigen an, wann eine neue Generation schlüpft. Das ist der optimale Behandlungszeitpunkt für B.t.k.",
      steps: [
        "Pheromonfalle (Lockstoff für Buchsbaumzünsler) im Gartenfachhandel kaufen",
        "Ab April aufhängen, 1,5 m Höhe, in Strauchnähe",
        "Wöchentlich kontrollieren – starker Falterflug zeigt bald schlüpfende Raupen an",
        "Ca. 10 Tage nach Fallen-Peak mit B.t.k. behandeln (dann sind Raupen jung und empfindlich)",
        "Pheromon-Köder alle 6–8 Wochen wechseln",
      ],
      effort: "EASY",
      durationMin: 10,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_buchszuensler_algenkalk",
      type: "HOME_REMEDY",
      style: ["ORGANIC"],
      title: "Algenkalk gegen Eiablage",
      description:
        "Algenkalk (Lithothamn) auf die Blätter gestrichen gilt als Hausmittel, das Falter von der Eiablage abhält. Wirkung begrenzt, aber schadstofffrei.",
      steps: [
        "Algenkalk (Lithothamn-Kalk) mit Wasser zu einem dünnflüssigen Brei anrühren",
        "Mit Pinsel oder Sprühflasche auf die Buchsblätter auftragen",
        "Alle 4 Wochen und nach starkem Regen erneuern",
        "Am besten vor dem Falterflug (ab April) beginnen",
      ],
      effort: "MEDIUM",
      durationMin: 30,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "LOW",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
  ],
  prevention: [
    "Pheromonfallen ab April aufstellen – erkennt erste Falter, bevor Raupen Schaden anrichten.",
    "Buchsbaum regelmäßig ins Innere schauen: schwarze Kotkrümel sind das früheste Warnsignal.",
    "Dichte Büsche auslichten – bessere Belüftung erschwert Faltern die versteckte Eiablage.",
    "Buchsbaum-Alternativen pflanzen (Ilex crenata, Heckenmyrte) bei chronischem Befall.",
    "Befallene Triebe sofort abschneiden und im Restmüll entsorgen – nie kompostieren.",
  ],
  sources: [SOURCES.JKI, SOURCES.LFL, SOURCES.GPP],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/7/7d/Cydalima_perspectalis20100725_2.jpg",
};
