import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const dickmaulruessler: ContentEntry = {
  id: "pest_dickmaulruessler",
  category: "PEST",
  name: "Dickmaulrüssler",
  scientificName: "Otiorhynchus sulcatus",
  aliases: ["Gefurchter Dickmaulrüssler"],
  description:
    "Der Gefurchte Dickmaulrüssler ist ein 8–12 mm langer, schwarzer Käfer, der nachtaktiv ist und typische Buchtenfrass-Spuren an Blatträndern hinterlässt. Während der Käfer nur kosmetische Schäden macht, sind die cremefarbenen Larven im Boden das eigentliche Problem: Sie fressen Wurzeln ab, was die Pflanze zum Welken und Absterben bringt – oft erst sichtbar, wenn der Schaden kaum noch reparabel ist.",
  traits: [
    "Käfer 8–12 mm, mattschwarz mit gelblichen Schuppenflecken, kann nicht fliegen",
    "Rüssel kurz und dick (namensgebend), nachtaktiv",
    "Typisches Schadbild: halbkreisförmige Buchten an Blatträndern (Käfer-Fraß)",
    "Larven cremeweiß, C-förmig, 10–15 mm, leben im Boden",
    "Larven fressen Wurzeln und Rinde am Wurzelhals – Pflanze welkt plötzlich ohne sichtbaren Grund",
  ],
  significance: "HARMFUL",
  defaultUrgency: "THIS_WEEK",
  habitat:
    "Larven im Boden von Rhododendron, Kirschlorbeer, Erdbeere, Buchs, Immergrün, Primeln; Käfer klettern nachts an Pflanzen; Kübelpflanzen besonders gefährdet",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED", "POTS"],
  confusionRisk: [
    {
      name: "Schneckenfraß",
      note: "Schnecken hinterlassen Schleimspuren und fressen unregelmäßiger; Dickmaulrüssler-Fraß ist charakteristisch halbkreisförmig an den Rändern.",
    },
    {
      name: "Blattlaus-Verrollung",
      note: "Blattlaus-Schäden zeigen Blattverformungen und Kolonien saugende Läuse, kein Buchtenfrass an Blatträndern.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_dickm_brettfallen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Brettfallen abends auslegen und Käfer absammeln",
      description:
        "Dickmaulrüssler verstecken sich tagsüber unter Brettern, Steinen oder Rindenstücken. Diese Verstecke kann man gezielt auslegen und die Käfer morgens absammeln.",
      steps: [
        "Abends feuchte Bretter, Kartonstreifen oder Jutesäcke unter befallenen Pflanzen auslegen",
        "Morgens früh (vor Sonnenaufgang) Bretter umdrehen",
        "Versteckte Käfer in Seifenwasser abwerfen und entsorgen",
        "Tipp: Taschenlampe mit abends kontrollieren – Käfer beim Klettern auf Stämmen absammeln",
        "Über 4–6 Wochen konsequent durchführen (Käfer leben 6–8 Wochen)",
      ],
      effort: "MEDIUM",
      durationMin: 20,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_dickm_nematoden",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "EFFECTIVE"],
      title: "Nematoden Heterorhabditis bacteriophora gegen Larven",
      description:
        "Parasitäre Fadenwürmer dringen in Larven ein und töten sie. Dieser Ansatz bekämpft den eigentlichen Schadverursacher. Zeitpunkt und Bedingungen sind entscheidend für die Wirkung.",
      steps: [
        "Nematoden (Heterorhabditis bacteriophora) im Fachhandel kaufen",
        "Nur anwenden bei Bodentemperatur über 12 °C (Mai–September)",
        "Boden vor der Anwendung gut bewässern",
        "Nematodenlösung nach Herstelleranleitung in Wasser anmischen",
        "Gleichmäßig auf die Wurzelzone gießen (Schlauch, Gießkanne ohne Sieb)",
        "Für 2–3 Wochen gleichmäßig feucht halten – Nematoden brauchen Feuchtigkeit",
        "Behandlung nach 4–6 Wochen wiederholen für vollständige Wirkung",
      ],
      effort: "MEDIUM",
      durationMin: 30,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_dickm_substratwechsel",
      type: "MECHANICAL",
      style: ["EFFECTIVE"],
      title: "Substrat bei Topfpflanzen komplett austauschen",
      description:
        "Bei Kübelpflanzen mit Larvenfund ist der Substratwechsel die sicherste und schnellste Lösung, um alle Larven zu entfernen.",
      steps: [
        "Pflanze vorsichtig aus dem Topf ziehen",
        "Gesamte alte Erde von den Wurzeln abschütteln und in Plastikbeutel entsorgen",
        "Wurzeln in lauwarmem Wasser abspülen und auf Larven absuchen",
        "Larven (cremeweiß, C-förmig) im Restmüll entsorgen",
        "Neues, frisches Substrat verwenden; Topf vorher mit heißem Wasser ausspülen",
        "Pflanze einpflanzen und gut angießen",
      ],
      effort: "HARD",
      durationMin: 60,
      timeframe: "THIS_WEEK",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_dickm_bodenpflege",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Bodenpflege und Mulchkontrolle",
      description:
        "Dickmaulrüssler-Weibchen legen Eier bevorzugt unter Mulchschichten und in Laubschichten ab. Regelmäßige Bodenpflege reduziert das Eiablagepotenzial.",
      steps: [
        "Mulchschichten nicht zu dicht auftragen – max. 5 cm",
        "Herbstlaub zeitnah entfernen, besonders unter Rhododendron",
        "Boden locker hacken – freiliegende Eier und Larven werden von Vögeln gefressen",
        "Hühner oder Enten (wenn vorhanden) gezielt über Beete lassen",
      ],
      effort: "EASY",
      durationMin: 30,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "LOW",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_dickm_manschetten",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Klebe-Manschetten an Stämmen und Töpfen anbringen",
      description:
        "Da Dickmaulrüssler nicht fliegen, müssen sie Stämme hochlaufen. Klebemittel oder Leimringe stoppen Käfer auf dem Weg nach oben.",
      steps: [
        "Raupenleim oder Klebefallen-Bänder im Gartenfachhandel kaufen",
        "Rund um den Stammfuß oder Topfrand aufkleben",
        "Regelmäßig (alle 4–6 Wochen) erneuern, besonders nach Regen",
        "Bei Topfpflanzen: Topf auf glatte Unterlagen stellen, von denen Käfer nicht klettern können",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
  ],
  prevention: [
    "Rhododendron, Kirschlorbeer und Erdbeeren regelmäßig auf Buchtenfrass an Blatträndern absuchen.",
    "Neue Pflanzen aus dem Handel auf Larven im Substrat überprüfen, bevor sie eingesetzt werden.",
    "Nematoden (H. bacteriophora) vorbeugend im Frühjahr und Spätsommer einbringen.",
    "Kletterunterlage am Stammfuß mit Klebering sichern – besonders bei Kübeln.",
    "Boden locker und für natürliche Feinde zugänglich halten: Igel, Vögel und Laufkäfer fressen Larven.",
  ],
  sources: [SOURCES.JKI, SOURCES.GPP, SOURCES.LFL],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/d/d1/Otiorrhynchus_sulcatus01.jpg",
};
