import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const schnecken: ContentEntry = {
  id: "pest_schnecken",
  category: "PEST",
  name: "Spanische Wegschnecke",
  scientificName: "Arion vulgaris",
  aliases: ["Nacktschnecke", "Rote Wegschnecke", "Killerschnecke"],
  description:
    "Die dominante Nacktschneckenart in deutschen Gärten. Ursprünglich aus Südwesteuropa eingewandert, frisst praktisch alles Junge und Saftige. Feuchte Frühjahre und Sommer = massive Plagen. Handeln erforderlich, sonst werden Salate, Jungpflanzen und Beete in Tagen kahl gefressen.",
  traits: [
    "6–15 cm lang, orange- bis ziegelrot, manchmal braun",
    "Kein Haus, nur feiner Schleimbelag",
    "Fraßschäden nachts und bei feuchtem Wetter",
    "Silbrige Schleimspuren am Morgen",
    "Eier im Spätsommer/Herbst in feuchter Erde abgelegt",
  ],
  significance: "HARMFUL",
  defaultUrgency: "IMMEDIATE",
  habitat: "Feuchte, schattige Gartenbereiche, Beete, Rasenränder, Komposthaufen",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED", "LAWN"],
  confusionRisk: [
    {
      name: "Tigerschnegel (Limax maximus)",
      note: "NÜTZLICH. Grau mit schwarzer Zeichnung, bis 20 cm lang – frisst Nacktschnecken-Eier. Nicht bekämpfen!",
    },
    {
      name: "Weinbergschnecke (Helix pomatia)",
      note: "Mit Haus, geschützt. Weniger schädlich, steht unter Naturschutz – nicht entfernen.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: true,
  },
  methods: [
    {
      id: "m_absammeln",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Konsequent absammeln (Abend/Nacht)",
      description:
        "Die effektivste und umweltfreundlichste Methode. Braucht Kontinuität: 2–3 Wochen tägliches Absammeln reduziert Population drastisch.",
      steps: [
        "Taschenlampe und Eimer mit Deckel bereitlegen",
        "Nach Sonnenuntergang oder bei Regen durch den Garten gehen",
        "Schnecken in Eimer sammeln (Handschuhe oder Stäbchen)",
        "Sofort töten: in heißem Wasser (>50°C) oder mit scharfem Messer zerteilen – das ist die tierschutzkonforme Methode",
        "NICHT salzen (qualvolle Tötung, rechtlich problematisch)",
        "Tote Schnecken im Restmüll, nicht im Kompost",
        "Täglich 2–3 Wochen durchziehen, dann nur noch wöchentlich",
      ],
      effort: "MEDIUM",
      durationMin: 30,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_schneckenkorn",
      type: "ORGANIC_PRODUCT",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Eisen-III-Phosphat-Schneckenkorn (Bio-zugelassen)",
      description:
        "Wirkstoff auf Basis von Eisen-III-Phosphat ist auch im Bio-Anbau zugelassen, verträglich für Igel, Vögel und Haustiere. NICHT das alte Metaldehyd-Schneckenkorn verwenden – das ist giftig für Haustiere und Igel.",
      steps: [
        "Produkt mit Wirkstoff 'Eisen-III-Phosphat' kaufen (z.B. Ferramol, Neudorff SchneckenKorn Bio)",
        "Nach Herstellerangabe ausstreuen – sparsam zwischen gefährdeten Pflanzen",
        "Vorzugsweise nach Regen oder abends",
        "Nach 10–14 Tagen Ausbringung wiederholen",
        "Nicht direkt auf Pflanzen oder essbare Teile streuen",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "THIS_WEEK",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_nematoden",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Nematoden gegen Schneckeneier",
      description:
        "Mikroskopische Fadenwürmer (Phasmarhabditis hermaphrodita) parasitieren Schnecken. Einmal jährlich im Frühjahr ausgebracht = deutlich reduzierte Population.",
      steps: [
        "Nematoden-Präparat im Fachhandel bestellen (Kühlpack-Versand)",
        "Im April/Mai oder September bei Bodentemperatur >5°C anwenden",
        "In Wasser auflösen und mit Gießkanne großflächig über Beete geben",
        "Boden 4–6 Wochen feucht halten",
        "Wirkt 6–8 Wochen, dann optional Wiederholung",
      ],
      effort: "EASY",
      durationMin: 45,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "INTERMEDIATE",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€€",
    },
    {
      id: "m_barrieren",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Barrieren um Beete",
      description:
        "Für Hochbeete, Salatreihen, Jungpflanzen: physische Sperren, die Schnecken nicht überwinden.",
      steps: [
        "Schneckenzaun (verzinktes Blech mit Umkantung) um gefährdete Beete",
        "Alternativ: Kupferband um Kübel und Hochbeetränder",
        "Sägespäne, Kaffeesatz oder Eierschalen-Barrieren (müssen trocken bleiben, Wirkung begrenzt)",
      ],
      effort: "MEDIUM",
      durationMin: 60,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
  ],
  prevention: [
    "Morgens gießen, nicht abends – feuchter Boden abends = Schneckenparty.",
    "Mulchen nur mit Rinde oder Sägespänen (trocken), nicht mit feuchtem Grasmulch.",
    "Versteckplätze reduzieren: Bretter, Steine, dichtes Bodenlaub regelmäßig entfernen.",
    "Laufenten, Igel und Tigerschnegel schützen – natürliche Fressfeinde.",
    "Im Herbst Boden flach umgraben – Gelege werden an die Oberfläche befördert und von Frost zerstört.",
  ],
  sources: [SOURCES.JKI, SOURCES.UBA, SOURCES.NABU],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/c/c3/Arion_vulgaris_3.jpg",
};
