import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const spinnmilben: ContentEntry = {
  id: "pest_spinnmilben",
  category: "PEST",
  name: "Spinnmilben",
  scientificName: "Tetranychus urticae",
  aliases: ["Rote Spinne", "Gemeine Spinnmilbe"],
  description:
    "Winzige Spinnentiere (0,3–0,5 mm), die bei Trockenheit und Hitze explosionsartig auftreten. Saugen an Blattzellen, hinterlassen feine Gespinste und lassen Blätter vergilben. Besonders gefährlich an Topfpflanzen und im Gewächshaus, weil dort die Luftfeuchtigkeit oft zu niedrig ist.",
  traits: [
    "0,3–0,5 mm groß, rötlich, gelblichgrün oder braun",
    "Feine, seidenähnliche Gespinste an Blattunterseiten und Triebspitzen",
    "Hellgelbe bis bronzefarbene Sprenkel auf Blattoberseiten (gesaugte Zellen)",
    "Bei Massenbefall verkrümeln und vertrocknen Blätter",
    "Bevorzugt trockene, heiße Standorte – fördernder Faktor Nummer eins",
  ],
  significance: "HARMFUL",
  defaultUrgency: "THIS_WEEK",
  habitat:
    "Blattunterseiten von fast allen Zierpflanzen, Gemüse (Bohnen, Gurken), Obstgehölzen und Topfpflanzen; bei hoher Temperatur und niedriger Luftfeuchte",
  seasons: ["SPRING", "SUMMER"],
  areas: ["GARDEN", "BED", "BALCONY", "POTS"],
  confusionRisk: [
    {
      name: "Thripse",
      note: "Thripse hinterlassen ähnliche silbrige Sprenkel, aber kein feines Gespinst. Thripse sind länglich und bewegen sich schnell.",
    },
    {
      name: "Wollläuse (Pseudococcidae)",
      note: "Wollläuse bilden auffällige weiße Wattebällchen in Blattachseln, kein flächiges Gespinst über Blättern.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_spinnmilben_abbrausen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Pflanze kräftig abduschen",
      description:
        "Wasserstrahl entfernt Milben und ihre Gespinste mechanisch und erhöht gleichzeitig die Luftfeuchtigkeit – dem wichtigsten Gegenmittel.",
      steps: [
        "Pflanze unter die Dusche oder an den Gartenschlauch stellen",
        "Blattunterseiten gezielt und kräftig abbrausen",
        "Auch Triebspitzen und Blattachseln gründlich behandeln",
        "Topfuntersetzer kurz abtropfen lassen",
        "Alle 2–3 Tage wiederholen, solange Befall sichtbar ist",
      ],
      effort: "EASY",
      durationMin: 10,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_spinnmilben_luftfeuchte",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Luftfeuchtigkeit erhöhen und mulchen",
      description:
        "Spinnmilben hassen Feuchtigkeit. Strukturelle Maßnahmen senken den Befallsdruck dauerhaft – besonders an Topfpflanzen und in trockenen Sommern.",
      steps: [
        "Topfpflanzen regelmäßig besprühen (morgens, damit Blätter nicht nass über Nacht stehen)",
        "Wasserschalen neben Pflanzen stellen",
        "Im Beet: 5–8 cm Mulchschicht aus Rindenmulch oder Rasenschnitt aufbringen",
        "Pflanzen an vollsonnigen Standorten an heißen Tagen zusätzlich schattieren",
        "Übermäßige Stickstoffdüngung vermeiden – weiche Triebe locken Milben an",
      ],
      effort: "EASY",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_spinnmilben_raubmilben",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Raubmilben Phytoseiulus persimilis einsetzen",
      description:
        "Die Raubmilbe Phytoseiulus persimilis ist der effektivste biologische Gegenspieler. Eine Raubmilbe frisst täglich bis zu 5 adulte Spinnmilben oder 20 Eier.",
      steps: [
        "Raubmilben im Fachhandel oder online bestellen (z. B. 1.000 Stück für 15–25 €)",
        "Lieferung sofort nach Ankunft anwenden – Raubmilben nicht lagern",
        "Vermikulit-Substrat mit Raubmilben gleichmäßig auf befallene Blätter streuen",
        "Temperatur muss über 15 °C liegen, Luftfeuchtigkeit über 60 %",
        "Insektizide und Akarizide für mindestens 6 Wochen vorher und nachher aussetzen",
        "Erfolg nach 2–3 Wochen sichtbar",
      ],
      effort: "MEDIUM",
      durationMin: 30,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_spinnmilben_neem",
      type: "ORGANIC_PRODUCT",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Neemöl-Präparat gegen Spinnmilben",
      description:
        "Neemöl wirkt als Kontaktmittel und stört den Häutungszyklus der Milben. Mehrfachbehandlung nötig, da Eier nicht abgetötet werden.",
      steps: [
        "Zugelassenes Neem-Produkt nach Herstellerangabe mischen",
        "Abends oder an bedecktem Tag sprühen – Blattunterseiten vollständig benetzen",
        "Nach 5–7 Tagen Wiederholungsbehandlung (Schlüpfen neuer Larven abdecken)",
        "Mindestens 3 Behandlungen für vollständige Wirkung",
        "Nicht bei Temperaturen über 30 °C anwenden – Verbrennungsgefahr",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "THIS_WEEK",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€€",
    },
  ],
  prevention: [
    "Pflanzen regelmäßig besprühen – Spinnmilben meiden hohe Luftfeuchtigkeit.",
    "Im Sommer mulchen: hält Boden feucht und senkt Bodentemperatur.",
    "Keine übermäßige Stickstoffdüngung – weiche Triebe sind bevorzugtes Futter.",
    "Neue Topfpflanzen zwei Wochen in Quarantäne stellen, bevor sie zu anderen kommen.",
    "Im Gewächshaus regelmäßig lüften und Bodenbereich befeuchten.",
  ],
  sources: [SOURCES.JKI, SOURCES.LFL],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/4/4e/Tetranychus_urticae_with_silk_threads.jpg",
};
