import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const trauermuecken: ContentEntry = {
  id: "pest_trauermuecken",
  category: "PEST",
  name: "Trauermücken",
  scientificName: "Sciaridae",
  aliases: [],
  description:
    "Kleine, schwarze Mücken (2–4 mm), die bevorzugt in feuchter Topferde leben. Die Adulten sind nur lästig, aber harmlos für Pflanzen. Gefährlich sind die weißlichen Larven im Substrat: Sie fressen Feinwurzeln und Wurzelhaare an, was besonders Sämlinge und schwache Pflanzen schädigt. Frische Blumenerde aus dem Baumarkt enthält oft schon Eier.",
  traits: [
    "Adulte Mücken 2–4 mm, schwarz, fliegen schwerfällig nahe der Topfoberfläche",
    "Larven 3–5 mm, weißlich-transparent mit schwarzem Kopfkapseln, leben im Substrat",
    "Vermehren sich in feuchter, humosreicher Topferde explosionsartig",
    "Ein Weibchen legt bis zu 200 Eier direkt auf die Substratoberfläche",
    "Befallspflanzen welken trotz ausreichender Bewässerung (Wurzelfraß)",
  ],
  significance: "NUISANCE",
  defaultUrgency: "THIS_WEEK",
  habitat:
    "Feuchtes Blumenerde-Substrat in Töpfen und Balkonkästen; bevorzugt torfhaltige, feine Erden; ganzjährig in Innenräumen",
  seasons: ["SPRING", "SUMMER", "AUTUMN", "WINTER"],
  areas: ["POTS", "BALCONY"],
  confusionRisk: [
    {
      name: "Fruchtfliegen (Drosophila)",
      note: "Fruchtfliegen fliegen um Obst und Küchenabfälle, nicht ums Substrat. Kein Wurzelschaden, keine Larven in der Erde.",
    },
    {
      name: "Weiße Fliege (Trialeurodes vaporariorum)",
      note: "Weiße Fliege sitzt auf Blattunterseiten und fliegt auf, wenn die Pflanze berührt wird. Kein Bezug zum Substrat.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_trauerm_austrocknen",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Substrat zwischen den Gießgängen antrocknen lassen",
      description:
        "Die einfachste und wirksamste Maßnahme. Trauermücken-Eier und -Larven sterben ab, wenn die oberen 2–3 cm des Substrats trocken werden. Macht aber nur Sinn, wenn die Pflanze Trockenheit verträgt.",
      steps: [
        "Finger-Test: erst gießen, wenn die oberen 2–3 cm des Substrats trocken sind",
        "Untersetzer nach dem Gießen nach 30 Minuten leeren – stehendes Wasser fördert Mücken",
        "Bei Bedarf Topfpflanze an einen helleren, wärmeren Platz stellen (trocknet Erde schneller)",
        "Konsequent 2–3 Wochen durchhalten – dann ist der Zyklus meist unterbrochen",
      ],
      effort: "EASY",
      durationMin: 5,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_trauerm_gelbtafeln",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Gelbtafeln gegen adulte Mücken",
      description:
        "Klebrige Gelbtafeln fangen die fliegenden Adulten ab und reduzieren die Neueiablage. Kein Allheilmittel alleine, aber gut als ergänzende Maßnahme.",
      steps: [
        "Gelbtafeln im Gartenfachhandel oder Baumarkt kaufen",
        "Direkt in das Substrat des befallenen Topfes stecken oder darüber hängen",
        "Bei starkem Befall pro Topf eine Tafel einsetzen",
        "Alle 2–3 Wochen oder wenn beidseitig voll austauschen",
        "Gleichzeitig Substrat austrocknen lassen für beste Wirkung",
      ],
      effort: "EASY",
      durationMin: 5,
      timeframe: "NOW",
      ecoScore: 4,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_trauerm_nematoden",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "EFFECTIVE"],
      title: "Nematoden Steinernema feltiae ins Substrat einbringen",
      description:
        "Mikroskopisch kleine Fadenwürmer, die gezielt Trauermückenlarven im Substrat befallen und töten. Sehr effektiv, bienensicher und für Mensch und Tier völlig harmlos.",
      steps: [
        "Nematoden (Steinernema feltiae) im Fachhandel kaufen – Produkte wie Nemaknock oder Nematop",
        "Lieferung sofort verwenden – Nematoden nicht lagern",
        "Nach Herstellerangabe in Wasser auflösen (ca. 500.000 Nematoden auf 2,5 l Wasser)",
        "Substrat erst gießen, bis es gut durchfeuchtet ist",
        "Nematodenlösung gleichmäßig übers Substrat gießen",
        "Substrat für 2 Wochen immer leicht feucht halten (Nematoden brauchen Feuchtigkeit zum Wandern)",
        "Temperatur muss über 10 °C liegen",
      ],
      effort: "MEDIUM",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_trauerm_sandmulch",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Sand- oder Lavamulch-Abdeckung",
      description:
        "Eine 1–2 cm dicke Schicht aus grobem Quarzsand oder Lavagranulat auf der Substratoberfläche hindert Weibchen an der Eiablage und lässt die Oberfläche schnell austrocknen.",
      steps: [
        "Grobkörnigen Quarzsand (Körnung 0,5–2 mm) oder Lavagranulat kaufen",
        "Oberfläche des Topfsubstrats leicht andrücken",
        "1–2 cm Sand oder Lava gleichmäßig aufschütten",
        "Beim Gießen direkt auf die Sandschicht gießen – Wasser sickert problemlos durch",
        "Schicht bleibt dauerhaft als Prävention",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_trauerm_zimt",
      type: "HOME_REMEDY",
      style: ["ORGANIC"],
      title: "Zimt auf die Substratoberfläche streuen",
      description:
        "Zimt hat eine leicht antimykotische Wirkung und soll Trauermückenweibchen von der Eiablage abhalten. Wirkt eher präventiv und bei leichtem Befall.",
      steps: [
        "Handelsüblichen Ceylon-Zimt (kein Kassia-Zimt) kaufen",
        "Dünne Schicht gleichmäßig auf die Substratoberfläche streuen",
        "Nach dem Gießen oder bei Regen erneuern",
        "Kombinieren mit dem Austrocknen-Lassen des Substrats für bessere Wirkung",
      ],
      effort: "EASY",
      durationMin: 5,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "LOW",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Ceylon-Zimt (gemahlen)"],
    },
  ],
  prevention: [
    "Neue Blumenerde nach dem Kauf sofort in luftdicht verschließbare Behälter umfüllen – Eier überleben nicht in ausgetrockneter Erde.",
    "Nicht unnötig gießen: Staunässe ist der wichtigste Faktor für Befall.",
    "Quarzsand oder Lavagranulat dauerhaft als Topfabdeckung verwenden.",
    "Neue Pflanzen 2 Wochen in Quarantäne stellen und auf Mücken beobachten.",
    "Torffreie, strukturstabile Erden bevorzugen – weniger Nährstoffangebot für Larven.",
  ],
  sources: [SOURCES.JKI, SOURCES.LFL],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl: "",
};
