import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const wolllaeuse: ContentEntry = {
  id: "pest_wolllaeuse",
  category: "PEST",
  name: "Wollläuse",
  scientificName: "Pseudococcidae",
  aliases: ["Schmierlläuse"],
  description:
    "Wollläuse sind 3–6 mm große, mit weißem Wachswolle überzogene Schildläuse. Sie sitzen in Blattachseln, an Triebspitzen und am Wurzelhals und saugen Pflanzensaft. Wie Blattläuse scheiden sie Honigtau aus, der Rußtaupilze fördert. Besonders an Kakteen, Sukkulenten, Orchideen und mediterranen Kübelpflanzen verbreitet.",
  traits: [
    "3–6 mm groß, von weißem Wachsfilz umhüllt (watteähnlich)",
    "Kolonien in Blattachseln, Triebspitzen und an Wurzeln",
    "Klebrige Honigtausekrete auf Blättern und Unterlage",
    "Schwarzer Rußtau auf dem Honigtau möglich",
    "Eier in weißen Wollpaketen an geschützten Stellen",
  ],
  significance: "HARMFUL",
  defaultUrgency: "THIS_WEEK",
  habitat:
    "Vor allem an Zimmer- und Kübelpflanzen, Kakteen und Sukkulenten; im Freien an Weinreben, Zitruspflanzen und mediterranen Pflanzen; bevorzugt trockene, warme Bedingungen",
  seasons: ["SPRING", "SUMMER", "AUTUMN", "WINTER"],
  areas: ["POTS", "BALCONY", "GARDEN"],
  confusionRisk: [
    {
      name: "Schildläuse (Coccidae, Diaspididae)",
      note: "Schildläuse sitzen fest auf Zweigen und Blattmittelrippen als braune, flache Schilder – kein Wollbelag.",
    },
    {
      name: "Echter Mehltau",
      note: "Mehltau bildet einen flächigen weißen Belag auf Blättern, keine einzelnen Wattebällchen in Blattachseln.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_wolll_abtupfen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Mit Alkohol oder Seifenwasser abtupfen",
      description:
        "Mühsame, aber sehr direkte Methode. Wachswolle schützt Wollläuse vor Sprühmitteln – mechanisches Entfernen ist daher oft wirksamer als Spritzen.",
      steps: [
        "Wattestäbchen in Isopropylalkohol (70%) oder stark verdünntes Seifenwasser tauchen",
        "Jede Wollläuse-Kolonie gezielt abtupfen und andrücken",
        "Wattestäbchen danach entsorgen – nicht wiederbenutzen",
        "Auch Blattachseln, Stängelansätze und Unterseiten absuchen",
        "Alle 5–7 Tage wiederholen – Eier schlüpfen nach und nach",
        "Bei Topfpflanzen: Wurzelbereich auf Wurzelwollläuse kontrollieren",
      ],
      effort: "HARD",
      durationMin: 30,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Isopropylalkohol 70 % oder Kali-Schmierseife"],
    },
    {
      id: "m_wolll_seife_spiritus",
      type: "HOME_REMEDY",
      style: ["ORGANIC", "BALANCED"],
      title: "Schmierseife-Spiritus-Lösung sprühen",
      description:
        "Kombination aus Seife (verklebt Atemöffnungen) und Spiritus (löst Wachswolle auf). Effektiver als Seife allein, da der Spiritus den schützenden Wollfilz durchdringt.",
      steps: [
        "1 EL Kali-Schmierseife und 1 EL Spiritus in 1 l lauwarmem Wasser mischen",
        "In Sprühflasche füllen und kräftig schütteln",
        "Abends oder an bewölktem Tag auf alle befallenen Stellen sprühen",
        "Besonders in Blattachseln und an Stängelansätzen einwirken lassen",
        "Nach 2–3 Tagen mit klarem Wasser abspülen",
        "Alle 5–7 Tage mindestens 3 Mal wiederholen",
      ],
      effort: "MEDIUM",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
      ingredients: [
        "Kali-Schmierseife 1 EL",
        "Spiritus 1 EL",
        "Wasser 1 l",
      ],
    },
    {
      id: "m_wolll_cryptolaemus",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "EFFECTIVE"],
      title: "Australischer Marienkäfer Cryptolaemus montrouzieri einsetzen",
      description:
        "Der spezialisierte Nützling frisst gezielt Wollläuse und ihre Eier. Besonders effektiv im Gewächshaus oder auf dem Balkon; im Freiland weniger sinnvoll.",
      steps: [
        "Cryptolaemus-Käfer im Fachhandel bestellen (z. B. 10–25 Stück je nach Befallsstärke)",
        "Lieferung sofort anwenden – nicht lagern",
        "Käfer abends auf befallene Pflanzen freisetzen",
        "Temperatur über 20 °C und ausreichend Beute sicherstellen",
        "4–6 Wochen keine Insektizide anwenden",
        "Kontrolle nach 3 Wochen – bei Rückgang des Befalls erfolgreich",
      ],
      effort: "MEDIUM",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€€",
    },
    {
      id: "m_wolll_neem",
      type: "ORGANIC_PRODUCT",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Neemöl-Präparat gegen Wollläuse",
      description:
        "Neemöl wirkt als Kontaktmittel und Fraßgift. Wegen des Wachsfilzes der Wollläuse sind mehrere Anwendungen nötig. Am besten kombiniert mit mechanischem Abtupfen.",
      steps: [
        "Wachswollkolonien vorher mit Wattestäbchen entfernen – erhöht die Wirkung erheblich",
        "Neem-Produkt nach Herstellerangabe mischen",
        "Abends auf alle befallenen Pflanzenteile sprühen",
        "Nach 7 Tagen Wiederholungsbehandlung",
        "Mindestens 3 Anwendungen für vollständige Wirkung",
      ],
      effort: "MEDIUM",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€€",
    },
  ],
  prevention: [
    "Neue Pflanzen grundsätzlich 2 Wochen in Quarantäne – Wollläuse schleichen sich oft mit zugekauften Pflanzen ein.",
    "Regelmäßig Blattachseln und Stängelansätze kontrollieren – frühes Erkennen spart viel Arbeit.",
    "Nicht zu warm und zu trocken stellen: mediterrane Zimmertemperaturen fördern Befall.",
    "Stickstoffüberdüngung vermeiden – weiche Pflanzenteile sind bevorzugter Befall.",
    "Ameisen von Kübeln fernhalten – sie schützen Wollläuse wie Blattläuse.",
  ],
  sources: [SOURCES.JKI, SOURCES.LFL, SOURCES.GPP],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/0/01/Mealybug_on_Kalanchoe.jpg",
};
