import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const echterMehltau: ContentEntry = {
  id: "disease_echter_mehltau",
  category: "DISEASE",
  name: "Echter Mehltau",
  scientificName: "Erysiphales",
  aliases: ["Mehltau", "Schönwetter-Pilz"],
  description:
    "Pilzkrankheit, die sich als weiß-mehliger Belag auf Blattoberseiten zeigt. Gegensatz zu Falschem Mehltau: Echter Mehltau liebt warme, trockene Tage und feuchte Nächte – klassisches 'Schönwetter-Problem'. Betrifft Rosen, Hortensien, Gurken, Weinreben, Stachelbeeren.",
  traits: [
    "Weißer, mehliger Belag v.a. auf Blattoberseiten",
    "Beginnt als kleine Flecken, breitet sich flächig aus",
    "Befallene Blätter werden gelb und fallen vorzeitig ab",
    "Bei Befall junger Triebe: verkümmertes Wachstum",
    "Abwischbar mit dem Finger (im Gegensatz zu Falschem Mehltau)",
  ],
  significance: "HARMFUL",
  defaultUrgency: "THIS_WEEK",
  habitat: "Rosen, Hortensien, Gurken, Kürbis, Zucchini, Weinreben, Beerensträucher",
  seasons: ["SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED", "BALCONY"],
  confusionRisk: [
    {
      name: "Falscher Mehltau",
      note: "Befall auf Blattunterseiten, grau-violetter Belag. Braucht feuchtes Wetter.",
    },
    {
      name: "Grauschimmel (Botrytis)",
      note: "Grauer, filzig-watteartiger Belag, oft an Blüten und weichen Teilen.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_entfernen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Befallene Blätter sofort entfernen",
      description:
        "Erste und wichtigste Maßnahme. Entfernt Sporenquelle, verhindert weitere Ausbreitung.",
      steps: [
        "Gartenschere mit 70%igem Alkohol desinfizieren",
        "Alle sichtbar befallenen Blätter an der Basis abschneiden",
        "In verschlossener Tüte im Restmüll entsorgen (NICHT kompostieren)",
        "Werkzeug und Hände nach Arbeit reinigen",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_milch",
      type: "HOME_REMEDY",
      style: ["ORGANIC", "BALANCED"],
      title: "Milch-Wasser-Lösung (1:9)",
      description:
        "Wissenschaftlich belegte Hausmittel-Wirkung. Milchsäurebakterien und Kalziumphosphate hemmen das Pilzwachstum. Rohmilch wirkt besser als H-Milch.",
      steps: [
        "100 ml Rohmilch (möglichst frisch) mit 900 ml Wasser mischen",
        "In saubere Sprühflasche füllen",
        "Frühmorgens oder abends auf Ober- UND Unterseiten aller Blätter sprühen",
        "Alle 3–4 Tage wiederholen, insgesamt 3–4 Behandlungen",
        "Nicht bei direkter Sonne anwenden",
      ],
      effort: "EASY",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Rohmilch 100 ml", "Wasser 900 ml"],
    },
    {
      id: "m_backpulver",
      type: "HOME_REMEDY",
      style: ["ORGANIC", "BALANCED"],
      title: "Natron-Spritzung",
      description:
        "Natron verändert den pH-Wert auf der Blattoberfläche und hemmt Pilzsporen.",
      steps: [
        "1 TL Natron + 1 TL Kernseife in 1 l warmem Wasser auflösen",
        "Abkühlen lassen, gründlich durchmischen",
        "Alle Pflanzenteile gleichmäßig besprühen",
        "Alle 7 Tage wiederholen bei anhaltendem Befall",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "THIS_WEEK",
      ecoScore: 4,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Natron 1 TL", "Kernseife 1 TL", "Wasser 1 l"],
    },
    {
      id: "m_schwefel",
      type: "ORGANIC_PRODUCT",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Netz-Schwefel (Bio-Fungizid)",
      description:
        "Zugelassenes Bio-Pflanzenschutzmittel. Sehr effektiv bei stärkerem Befall. Nicht bei Hitze (>28°C) anwenden – Verbrennungsgefahr.",
      steps: [
        "Netz-Schwefel-Produkt nach Herstellerangabe dosieren",
        "Bei bewölktem Wetter oder am Abend sprühen",
        "Alle Pflanzenteile gleichmäßig benetzen",
        "Im Abstand von 10–14 Tagen wiederholen",
        "Wartezeiten bei Nutzpflanzen einhalten",
      ],
      effort: "MEDIUM",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_standort",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Standort und Pflege anpassen",
      description:
        "Langfristige Prävention. Luftiger Stand + richtige Bewässerung reduziert Mehltau drastisch.",
      steps: [
        "Pflanzabstand prüfen: Rosen mind. 50 cm, Hortensien 80–100 cm",
        "Starken Rückschnitt dichter Bestände zur Belüftung",
        "Nur am Boden gießen, nicht über die Blätter",
        "Nicht abends gießen – Blätter sollen nachts trocken sein",
        "Bei Neupflanzungen: mehltauresistente Sorten wählen",
      ],
      effort: "MEDIUM",
      durationMin: 60,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
  ],
  prevention: [
    "Resistente Sorten kaufen – bei Rosen ADR-geprüfte Sorten, bei Gurken pilzresistente F1-Hybride.",
    "Ausreichend Pflanzabstand einhalten für Luftzirkulation.",
    "Morgens gießen, Blätter trocken halten.",
    "Stickstoffüberschuss vermeiden – macht Pflanzen anfällig.",
    "Im Herbst befallenes Laub komplett entfernen (Sporenüberwinterung).",
  ],
  sources: [SOURCES.JKI, SOURCES.GPP, SOURCES.LFL],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/7/7b/UncinulaTulasneiLeaf.jpg",
};
