import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const grauschimmel: ContentEntry = {
  id: "disease_grauschimmel",
  category: "DISEASE",
  name: "Grauschimmel",
  scientificName: "Botrytis cinerea",
  aliases: ["Botrytis"],
  description:
    "Universalpilz, der nahezu alle weichen Pflanzenteile befällt. Typisch ist ein grauer, filzig-watteartiger Belag an Blütenbasis, weichen Trieben und faulenden Früchten. Breitet sich bei feuchtkaltem Wetter rasend schnell aus. Betroffen sind Erdbeeren, Tomaten, Pelargonien, Cyclamen, Salat und viele Stauden. Grauschimmel gilt als der wirtschaftlich bedeutendste Pflanzenpilz im Gartenbau.",
  traits: [
    "Grauer, watteartiger (NICHT mehlig-pulvriger) Belag auf Blüten, Früchten und Trieben",
    "Weiches, braun-wässriges Faulen des befallenen Gewebes",
    "Schwarz-braune Stängelflecken (Sklerotien) bei längerem Befall",
    "Befall tritt vor allem bei Feuchtigkeit, dichtem Stand und schlechter Belüftung auf",
    "Sporenwolke beim Bewegen befallener Pflanzenteile sichtbar",
  ],
  significance: "HARMFUL",
  defaultUrgency: "IMMEDIATE",
  habitat:
    "Erdbeeren, Tomaten, Salat, Stauden, Pelargonien, Cyclamen; gemüsereiche Beete, dichter Bestand, schlechte Belüftung",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED", "BALCONY", "POTS"],
  confusionRisk: [
    {
      name: "Echter Mehltau",
      note: "Weißer mehlig-pulvriger Belag (nicht wattig), trocken abwischbar, bevorzugt Blattoberseiten.",
    },
    {
      name: "Sclerotinia-Weißstängelfäule",
      note: "Härterer watteartiger Belag mit schwarzen Sklerotien im Stängelinneren.",
    },
    {
      name: "Wurzelfäule",
      note: "Pflanze welkt komplett ohne sichtbaren Oberflächenbelag, Problem liegt unter der Erde.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_befallenes_entfernen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Befallene Teile sofort entfernen",
      description:
        "Wichtigste und dringlichste Maßnahme. Grauschimmel produziert bei Störung sofort Sporenwolken — deshalb befallene Teile vorsichtig, ohne Erschütterung, entfernen und direkt in eine Tüte. Im Restmüll entsorgen.",
      steps: [
        "Gartenschere mit 70%igem Alkohol desinfizieren",
        "Befallene Pflanzenteile möglichst ohne Erschütterung abschneiden — Sporenwolke vermeiden",
        "Direkt in eine verschlossene Tüte packen — NICHT kompostieren",
        "Nach der Arbeit Schere und Hände reinigen",
        "Pflanze anschließend auslichten, damit Luft besser zirkulieren kann",
      ],
      effort: "EASY",
      durationMin: 20,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_auslichten",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Bestand auslichten und Mulch unter Erdbeeren",
      description:
        "Dichter Stand ist der wichtigste Risikofaktor. Durch Auslichten trocknen Pflanzen nach Regen schneller. Stroh oder Rindenmulch unter Erdbeeren hält Früchte vom feuchten Boden fern.",
      steps: [
        "Innere Blätter und bodennahe Triebe bei dicht stehenden Pflanzen entfernen",
        "Unter Erdbeeren Stroh ausbreiten — hält Früchte trocken und sauber",
        "Tomatenreihen: untere Blätter bis 30 cm über Boden entfernen",
        "Pflanzabstände bei Neupflanzung großzügig wählen",
      ],
      effort: "MEDIUM",
      durationMin: 45,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_bacillus",
      type: "BIOLOGICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Bacillus subtilis (Serenade o. ä.) als biologisches Fungizid",
      description:
        "Biologisches Pflanzenschutzmittel auf Basis des Bodenbakteriums Bacillus subtilis. Wirkt vorbeugend und kurativ gegen Botrytis. Wartezeiten bei Nutzpflanzen einhalten (je nach Produkt). Am wirksamsten als vorbeugende Behandlung bei Risikowetter.",
      steps: [
        "Produkt nach Herstellerangabe dosieren (z. B. Serenade ASO)",
        "Vorbeugend bei feuchtkühlem Wetter oder nach Regen sprühen",
        "Alle Pflanzenteile gleichmäßig benetzen",
        "Alle 7–10 Tage bei anhaltend feucht-kühlem Wetter wiederholen",
        "Wartezeit bis Ernte beachten (häufig 1 Tag)",
      ],
      effort: "MEDIUM",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 4,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_giessen_hygiene",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Morgens gießen und Pflanzenhygiene",
      description:
        "Feuchtigkeit und stehendes Wasser sind Haupttreiber von Botrytis. Morgens gießen, damit Pflanzen bis Abend abtrocknen. Abgestorbene Blüten- und Blattteile regelmäßig entfernen.",
      steps: [
        "Nur morgens gießen — Pflanzen bis Abend abtrocknen lassen",
        "Ausschließlich am Boden gießen, nie über die Blätter",
        "Verwelkte Blüten und abgestorbene Blätter regelmäßig entfernen",
        "Stickstoff-Düngung mäßig halten — üppiges weiches Gewebe ist anfälliger",
      ],
      effort: "EASY",
      durationMin: 15,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_tomaten_kulturmassnahmen",
      type: "CULTURAL",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Tomaten: untere Blätter entfernen und Folientunnel mit Lüftung",
      description:
        "Spezielle Maßnahme für Tomaten. Untere Blätter bis 30 cm entfernen reduziert Spritzwasser vom Boden. Folientunnel hält Laub trocken, muss aber gut belüftet sein um Hitze und Kondensation zu vermeiden.",
      steps: [
        "Alle Blätter bis 30 cm über Boden entfernen",
        "Ausreichend Reihenabstand einhalten (mind. 60 cm zwischen Tomatenpflanzen)",
        "Folientunnel oder Überdachung mit seitlicher Öffnung installieren",
        "Täglich lüften — kein Stau von Feuchtigkeitsluft unter der Folie",
        "Regelmäßig ausgeizen (Seitengeize entfernen) für bessere Durchlüftung",
      ],
      effort: "HARD",
      durationMin: 90,
      timeframe: "LONG_TERM",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
  ],
  prevention: [
    "Ausreichend Pflanzabstand einhalten — Luftzirkulation ist die beste Vorbeugung.",
    "Morgens gießen, Blätter so trocken wie möglich halten.",
    "Stickstoff-Düngung mäßig halten — weiches Gewebe ist anfälliger.",
    "Befallenes Pflanzenmaterial immer vollständig aus dem Beet entfernen.",
    "Stroh oder Mulch unter Erdbeeren gegen Bodenfeuchtigkeit.",
    "Dichten Bestand regelmäßig auslichten.",
  ],
  sources: [SOURCES.JKI, SOURCES.LFL, SOURCES.GPP],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Botrytis_cinerea_on_Solanum_lycopersicum.jpg/320px-Botrytis_cinerea_on_Solanum_lycopersicum.jpg",
};
