import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const kraeuselkrankheit: ContentEntry = {
  id: "disease_kraeuselkrankheit",
  category: "DISEASE",
  name: "Kräuselkrankheit",
  scientificName: "Taphrina deformans",
  aliases: ["Pfirsich-Kräuselkrankheit"],
  description:
    "Pilzkrankheit an Pfirsich, Nektarine und Mandel, die im zeitigen Frühjahr beim Austrieb beginnt. Jungtriebe und Blätter werden blasig deformiert, verdickt und gekräuselt; die Farbe wechselt von rötlich zu weisslich-mehlig. Bei starkem Befall fallen die Blätter ab und die Ernte wird massiv reduziert. Der Baum treibt nach wenigen Wochen gesund nach, bleibt jedoch geschwächt.",
  traits: [
    "Blasige, stark gewellte und gekräuselte Blätter beim Austrieb",
    "Verdickte, lederartige Blattstruktur, anfangs rötlich, später weisslich-mehlig",
    "Pilzbelag (Ascosporen) gibt Blättern mehliges Aussehen",
    "Befallene Blätter fallen nach wenigen Wochen ab",
    "Baum treibt gesund nach, bleibt aber geschwächt und trägt weniger",
  ],
  significance: "HARMFUL",
  defaultUrgency: "THIS_WEEK",
  habitat:
    "Pfirsich, Nektarine, Mandel — alle Sorten betroffen, manche robuster (z. B. 'Roter Ellerstädter', 'Benedicte')",
  seasons: ["SPRING"],
  areas: ["GARDEN"],
  confusionRisk: [
    {
      name: "Blattlausbefall",
      note: "Blattkräuselung beginnt von der Triebspitze, Läuse sichtbar auf Unterseiten.",
    },
    {
      name: "Frostschaden",
      note: "Gleichmäßige Schädigung ohne Blasenbildung, keine Sporenbelag.",
    },
    {
      name: "Echter Mehltau",
      note: "Mehlig-weisser Belag, aber keine blasige Verformung des Gewebes.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_kupfer_knospe",
      type: "ORGANIC_PRODUCT",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Kupfer-Spritzung zur Knospenzeit (kritisches Timing)",
      description:
        "Wirksamste Maßnahme gegen Kräuselkrankheit — aber nur im richtigen Zeitfenster: wenn Knospen schwellen, aber noch geschlossen sind (typisch Februar bis Anfang März). Sobald die grüne Blattspitze sichtbar ist, ist die Spritzung wirkungslos. Kupferpräparate sind bio-zugelassen, aber ökologisch belastend — sparsam und gezielt einsetzen.",
      steps: [
        "Wetterfenster abpassen: kein Regen für mindestens 4–6 Stunden nach Anwendung",
        "Kupferpräparat nach Herstellerangabe dosieren (z. B. Cuprozin Progress)",
        "Baum vollständig benetzen — Stamm, Äste und Knospen eingeschlossen",
        "Bei warmer Witterung (>10 °C) und geschlossenen Knospen anwenden",
        "Einmalige Behandlung in der Regel ausreichend — nur bei sehr starkem Vorjahresbefall zweimal",
      ],
      effort: "MEDIUM",
      durationMin: 30,
      timeframe: "SEASONAL",
      ecoScore: 3,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_befallene_triebe",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Befallene Triebe und Blätter ausschneiden",
      description:
        "Wenn der Befall bereits sichtbar ist, befallene Triebe und Blätter sofort entfernen. Reduziert den Sporenherd und schont die Pflanze. Ins Restmüll — nicht kompostieren.",
      steps: [
        "Schere mit 70%igem Alkohol desinfizieren",
        "Alle sichtbar befallenen Triebspitzen und Blätter abschneiden",
        "In verschlossener Tüte im Restmüll entsorgen",
        "Schnittwunden ggf. mit Baumwachs verschließen",
        "Werkzeug nach Arbeit reinigen",
      ],
      effort: "EASY",
      durationMin: 20,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_schachtelhalm_kraeusel",
      type: "HOME_REMEDY",
      style: ["ORGANIC"],
      title: "Ackerschachtelhalm-Brühe zur Stärkung",
      description:
        "Kieselsäurereiche Brühe stärkt das Gewebe vorbeugend. Im Herbst nach dem Laubfall und kurz vor dem Austrieb im Frühjahr anwenden. Kein direktes Fungizid, unterstützt aber die Pflanzenabwehr.",
      steps: [
        "150 g frischen Ackerschachtelhalm in 1 l Wasser 24 h einweichen",
        "30 Minuten köcheln, abkühlen, abseihen",
        "1:5 mit Wasser verdünnen",
        "Auf Stamm und Äste sprühen — vorbeugend im Herbst und im Februar",
      ],
      effort: "MEDIUM",
      durationMin: 40,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "LOW",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Ackerschachtelhalm 150 g frisch", "Wasser 1 l"],
    },
    {
      id: "m_regendach",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Regendach oder Folientunnel über dem Baum",
      description:
        "Hocheffektiv, weil die Kräuselkrankheit Feuchtigkeit für die Sporenkeimung benötigt. Ein einfaches Regendach aus Folie über Spalierbäumen oder Kübelpfirsichen verhindert Befall zu über 80 %. Aufwand lohnt sich besonders für Spalierpfirsiche oder Kübelhaltung.",
      steps: [
        "Folie oder Gewächshausfolie über dem Baum spannen — ab Knospenaustrieb bis Ende Blüte",
        "Seiten offen lassen für Luftzirkulation und Bestäubung",
        "Ab Ende Mai / wenn Blätter ausgehärtet: Folie entfernen",
        "Im Herbst Folie reinigen und einlagern für das nächste Jahr",
      ],
      effort: "HARD",
      durationMin: 120,
      timeframe: "SEASONAL",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_resistente_sorten",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Resistente Sorten bei Neupflanzung wählen",
      description:
        "Langfristig wirksamste Lösung. Manche Pfirsichsorten zeigen deutlich bessere Toleranz gegenüber Kräuselkrankheit und kommen mit weniger oder keiner Spritzung aus.",
      steps: [
        "Bei Neupflanzung robuste Sorten wählen: 'Roter Ellerstädter', 'Benedicte', 'Revita', 'Rekord aus Alfter'",
        "Fachhandel nach aktuell verfügbaren tolieranten Sorten befragen",
        "Standort mit gutem Luftzug wählen (weniger Feuchte = weniger Befall)",
      ],
      effort: "EASY",
      durationMin: 30,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
  ],
  prevention: [
    "Kupfer-Spritzung im richtigen Zeitfenster (Knospen schwellen, noch geschlossen, Feb./März).",
    "Regendach oder Folientunnel über Spalierpfirsichen im Frühjahr.",
    "Resistente Sorten wählen: 'Roter Ellerstädter', 'Benedicte', 'Revita'.",
    "Befallenes Laub im Herbst vollständig entfernen und im Restmüll entsorgen.",
    "Ackerschachtelhalm-Brühe im Herbst und vor Austrieb zur Stärkung.",
  ],
  sources: [SOURCES.JKI, SOURCES.GPP, SOURCES.LFL],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Taphrina_deformans_on_peach.jpg/320px-Taphrina_deformans_on_peach.jpg",
};
