import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const krautBraunfaeule: ContentEntry = {
  id: "disease_kraut_braunfaeule",
  category: "DISEASE",
  name: "Kraut- und Braunfäule",
  scientificName: "Phytophthora infestans",
  aliases: ["Tomatenfäule", "Kartoffelfäule"],
  description:
    "Aggressive Pilzerkrankung, die ganze Tomaten- und Kartoffelbestände in Tagen vernichten kann. Historisch verantwortlich für die Große Irische Hungersnot 1845. Wird durch feucht-warmes Wetter begünstigt. Bei Verdacht: sofort handeln.",
  traits: [
    "Große, unregelmäßige braune Flecken auf Blättern",
    "Rand der Flecken oft blassgrün",
    "Bei Feuchtigkeit: weißer Belag auf Blattunterseiten",
    "Schwarz-braune Stellen an Stängeln und Stielen",
    "Braune, harte Flecken auf Früchten – werden ungenießbar",
  ],
  significance: "DANGEROUS",
  defaultUrgency: "IMMEDIATE",
  habitat: "Tomaten (besonders Freiland), Kartoffeln",
  seasons: ["SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED", "POTS"],
  confusionRisk: [
    {
      name: "Dürrfleckenkrankheit (Alternaria)",
      note: "Ähnliche braune Flecken, aber mit konzentrischen Ringen. Weniger aggressiv.",
    },
    {
      name: "Blütenendfäule",
      note: "Nur an Fruchtspitze, schwarz-eingesunken – kein Pilz, sondern Kalziummangel.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
    notes:
      "Befallene Früchte nicht verzehren (können Toxine enthalten). Ernteverluste oft total bei spätem Eingreifen.",
  },
  methods: [
    {
      id: "m_sofort_entfernen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Befallene Pflanze SOFORT entfernen",
      description:
        "Bei eindeutigem Befall (braune Stiele + Flecken): keine Heilung mehr möglich. Jede Stunde zählt, sonst geht Nachbarbestand verloren.",
      steps: [
        "Mit scharfer Schere komplette Pflanze bodennah abschneiden",
        "In verschlossener Tüte sofort zum Restmüll – nicht kompostieren",
        "Umliegende Erde 5–10 cm tief abtragen und entfernen",
        "Werkzeug, Stäbe und Bänder mit 70%igem Alkohol desinfizieren",
        "Hände gründlich waschen, Kleidung wechseln",
        "Nachbarpflanzen 14 Tage täglich kontrollieren",
      ],
      effort: "MEDIUM",
      durationMin: 40,
      timeframe: "NOW",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_regenschutz",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Tomaten-Regendach installieren",
      description:
        "Die wichtigste präventive Maßnahme. Nasse Blätter = Infektionsrisiko. Ein einfaches Vordach reduziert Befall um 80–90%.",
      steps: [
        "Freilandtomaten überdachen: Tomatenhaus, Folientunnel oder einfaches Plexiglas-Vordach",
        "Seitlich offen lassen für Luftzirkulation",
        "Unteren Bereich der Pflanze freihalten (keine Bodennähe)",
        "Regenwasser ableiten, NICHT auf die Beete",
      ],
      effort: "HARD",
      durationMin: 180,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€€",
    },
    {
      id: "m_kupfer",
      type: "ORGANIC_PRODUCT",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Kupferpräparat (nur als letzte Option)",
      description:
        "Bio-zugelassen, aber Kupfer reichert sich im Boden an. Nur bei akuter Bedrohung und ohne Überdachungs-Option einsetzen.",
      steps: [
        "Zugelassenes Kupferpräparat nach Herstellerangabe mischen",
        "Bei ersten Anzeichen oder nach Regenperioden spritzen",
        "Alle Pflanzenteile benetzen, auch Blattunterseiten",
        "Höchstens 2–3× pro Saison – Umweltauflagen beachten",
        "Wartezeit bei Ernte einhalten",
      ],
      effort: "MEDIUM",
      durationMin: 30,
      timeframe: "THIS_WEEK",
      ecoScore: 2,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: false,
      safeForPets: false,
      costEur: "€€",
    },
    {
      id: "m_resistente_sorten",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Auf resistente Sorten umstellen",
      description:
        "Moderne Züchtungen sind deutlich widerstandsfähiger. Die beste Langzeitlösung.",
      steps: [
        "Nächste Saison resistente Sorten wählen: 'Phantasia F1', 'De Berao', 'Resi', 'Philovita F1'",
        "Beim Kauf auf Label 'phytophthora-tolerant' achten",
        "Fruchtfolge beachten: 3–4 Jahre keine Nachtschattengewächse auf gleicher Fläche",
      ],
      effort: "EASY",
      durationMin: 20,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
  ],
  prevention: [
    "Pflanzabstand mindestens 60 cm zwischen Tomaten für Luftzirkulation.",
    "Nur am Boden gießen (Tropfschlauch ideal), nie über die Blätter.",
    "Untere Blätter konsequent entfernen – kein Bodenkontakt.",
    "Mulchen mit Stroh, um Spritzwasser-Infektion zu verhindern.",
    "Keine Kartoffeln in der Nähe von Tomaten – gleicher Erreger, Ansteckungsgefahr.",
    "DWD-Wetterwarnung 'Krautfäule-Gefahr' beachten und vorbeugend handeln.",
  ],
  sources: [SOURCES.JKI, SOURCES.DWD, SOURCES.LFL],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/9/92/Phytophtora_infestans-effects.jpg",
};
