import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const rosenrost: ContentEntry = {
  id: "disease_rosenrost",
  category: "DISEASE",
  name: "Rosenrost",
  scientificName: "Phragmidium mucronatum",
  aliases: ["Rost"],
  description:
    "Häufige Pilzerkrankung an Rosen. Orange-braune Sporenlager auf Blattunterseiten, gelbe Flecken oben. Schwächt die Pflanze, führt zu frühzeitigem Blattfall. Bei anhaltendem Befall über Jahre kann die Rose eingehen.",
  traits: [
    "Gelbe bis rötliche Flecken auf Blattoberseiten",
    "Orange bis dunkelbraune Sporenlager auf Blattunterseiten",
    "Später: schwarze Winterlager",
    "Vorzeitiger Blattfall",
    "Bei starkem Befall: verkrüppelte Triebe",
  ],
  significance: "HARMFUL",
  defaultUrgency: "THIS_WEEK",
  habitat: "Rosen aller Arten, besonders anfällige Sorten",
  seasons: ["SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED"],
  confusionRisk: [
    {
      name: "Sternrußtau (Diplocarpon rosae)",
      note: "Schwarze Flecken mit strahlig ausfransendem Rand. Häufiger als Rosenrost.",
    },
    {
      name: "Echter Mehltau",
      note: "Weißer, mehliger Belag statt orange-brauner Pusteln.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_laub_entfernen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Befallene Blätter und Herbstlaub entfernen",
      description:
        "Die wichtigste Maßnahme. Sporen überwintern am Falllaub – was im Herbst liegen bleibt, infiziert im Frühjahr neu.",
      steps: [
        "Alle befallenen Blätter der Rose abpflücken",
        "Im Herbst/Winter alle Falllaub unter der Rose wegräumen",
        "Boden unter der Rose gründlich harken",
        "Alles in Restmüll oder verbrennen – NICHT kompostieren",
        "Bei Nachbarrosen gleiche Prozedur",
      ],
      effort: "EASY",
      durationMin: 30,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_schachtelhalm",
      type: "HOME_REMEDY",
      style: ["ORGANIC"],
      title: "Schachtelhalm-Brühe als Stärkungsmittel",
      description:
        "Ackerschachtelhalm enthält viel Kieselsäure, die Pflanzenzellen stärkt. Klassisches Bio-Mittel, gute Präventionswirkung.",
      steps: [
        "150 g getrockneten Ackerschachtelhalm in 1,5 l Wasser 24 h einweichen",
        "30 Min köcheln, abseihen",
        "1:5 mit Wasser verdünnen",
        "Alle 10–14 Tage ab Austrieb auf Rose sprühen",
        "Präventiv über die gesamte Saison anwenden",
      ],
      effort: "MEDIUM",
      durationMin: 60,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "INTERMEDIATE",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Getrockneter Ackerschachtelhalm 150 g", "Wasser 1,5 l"],
    },
    {
      id: "m_fungizid",
      type: "ORGANIC_PRODUCT",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Bio-Fungizid (Netz-Schwefel oder Lecithin-Produkt)",
      description:
        "Bei stärkerem Befall im Fachhandel erhältliche Bio-Fungizide einsetzen.",
      steps: [
        "Produkt auf Basis von Netz-Schwefel oder Lecithin (z.B. 'Celaflor Pilzfrei Ectivo') wählen",
        "Herstellerangaben exakt befolgen",
        "Abends oder bei bedecktem Wetter sprühen",
        "Alle 10–14 Tage wiederholen",
        "Nicht bei Hitze über 28°C – Verbrennungsgefahr",
      ],
      effort: "EASY",
      durationMin: 20,
      timeframe: "THIS_WEEK",
      ecoScore: 4,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_sortenwahl",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "ADR-Rosen – resistent ab Werk",
      description:
        "ADR-geprüfte Rosen sind unabhängig auf Robustheit getestet. Die beste Langzeitlösung.",
      steps: [
        "Bei Neupflanzung ADR-Rose wählen (Zertifikat am Etikett)",
        "Beispiele: 'Bienenweide', 'Knock Out', 'Mirato', 'Lions-Rose'",
        "Kranke Altrosen bei wiederholtem Befall ersetzen",
      ],
      effort: "MEDIUM",
      durationMin: 120,
      timeframe: "SEASONAL",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€€€",
    },
  ],
  prevention: [
    "Ausreichend luftiger Stand – mindestens 60 cm zwischen Rosen.",
    "Nur am Boden gießen, nie über die Blätter.",
    "Morgens gießen, damit Boden bis Mittag abtrocknet.",
    "Ausgewogen düngen: Kalium stärkt Zellwände, Stickstoffüberschuss macht anfällig.",
    "Rosen nicht in Rosen-Nachbarschaft pflanzen (Boden-Müdigkeit).",
  ],
  sources: [SOURCES.JKI, SOURCES.GPP],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/9/95/Phragmidium_mucronatum_BW54.jpg",
};
