import type { ContentEntry } from "@/domain/types";
import { CONTENT_VERSION, SOURCES } from "../_shared";

export const sternrusstau: ContentEntry = {
  id: "disease_sternrusstau",
  category: "DISEASE",
  name: "Sternrußtau",
  scientificName: "Diplocarpon rosae",
  aliases: ["Schwarzfleckenkrankheit"],
  description:
    "Häufigste Rosenkrankheit in deutschen Gärten. Charakteristisch sind sternförmig auslaufende schwarze Flecken auf der Blattoberseite mit gelblichen Halos, die zum vorzeitigen Blattfall führen. Befallene Pflanzen schwächen sich kumulativ über die Jahre, da der Pilz auf abgefallenem Laub überwintert und im Frühjahr erneut ausbricht.",
  traits: [
    "Schwarze, sternförmig ausgefranste Flecken auf Blattoberseiten",
    "Gelbe Aufhellungen (Halos) rund um die Flecken",
    "Blattfall beginnt von unten nach oben",
    "Pilz überdauert auf abgefallenem Laub am Boden",
    "Befallsstärke nimmt bei anfälligen Sorten ohne Hygienemaßnahmen jedes Jahr zu",
  ],
  significance: "HARMFUL",
  defaultUrgency: "THIS_WEEK",
  habitat:
    "Rosen — anfällige Sorten (alte Edelrosen, manche Beetrosen); ADR-Sorten meist deutlich robuster",
  seasons: ["SPRING", "SUMMER", "AUTUMN"],
  areas: ["GARDEN", "BED"],
  confusionRisk: [
    {
      name: "Echter Mehltau",
      note: "Weißer mehliger Belag auf Blattoberseite — keine sternförmigen Flecken.",
    },
    {
      name: "Falscher Mehltau",
      note: "Grau-violetter Belag auf Blattunterseiten, Befall bei feucht-kühlem Wetter.",
    },
    {
      name: "Rosenrost",
      note: "Orangefarbene Sporenlager auf Blattunterseiten, keine schwarzen Flecken.",
    },
  ],
  safety: {
    toxicToChildren: false,
    toxicToPets: [],
    allergyRisk: false,
    invasive: false,
  },
  methods: [
    {
      id: "m_laub_entfernen",
      type: "MECHANICAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "Befallenes Laub konsequent entfernen",
      description:
        "Wichtigste Einzelmaßnahme. Alle befallenen Blätter — am Boden liegende eingeschlossen — sammeln und im Restmüll entsorgen. Unterbricht die Sporenüberwinterung und reduziert den Infektionsdruck im nächsten Jahr spürbar.",
      steps: [
        "Alle sichtbar befallenen Blätter von der Pflanze abzupfen",
        "Abgefallenes Laub unter den Rosen vollständig aufsammeln",
        "In verschlossener Tüte im Restmüll entsorgen — NICHT kompostieren",
        "Im Herbst Laubfall vollständig beseitigen und Mulch erneuern",
        "Schere nach Arbeit mit Alkohol desinfizieren",
      ],
      effort: "EASY",
      durationMin: 20,
      timeframe: "NOW",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_schachtelhalm",
      type: "HOME_REMEDY",
      style: ["ORGANIC", "BALANCED"],
      title: "Ackerschachtelhalm-Brühe als Stärkungsmittel",
      description:
        "Kieselsäurereiche Brühe aus Ackerschachtelhalm stärkt das Blattgewebe und erhöht die Widerstandskraft gegen Pilzinfektionen. Vorbeugend wirksam, kein direktes Fungizid.",
      steps: [
        "150 g frischen oder 15 g getrockneten Ackerschachtelhalm in 1 l Wasser einweichen (12–24 h)",
        "Ansatz 30 Minuten köcheln, abkühlen lassen, abseihen",
        "1:5 mit Wasser verdünnen und in Sprühflasche füllen",
        "Morgens auf Blattober- und -unterseiten sprühen",
        "Alle 10–14 Tage wiederholen, vorbeugend ab Austrieb",
      ],
      effort: "MEDIUM",
      durationMin: 40,
      timeframe: "THIS_WEEK",
      ecoScore: 5,
      successRate: "LOW",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
      ingredients: ["Ackerschachtelhalm 150 g frisch / 15 g getrocknet", "Wasser 1 l"],
    },
    {
      id: "m_netzschwefel",
      type: "ORGANIC_PRODUCT",
      style: ["BALANCED", "EFFECTIVE"],
      title: "Netzschwefel oder Kupferpräparat bei starkem Befall",
      description:
        "Zugelassene Bio-Fungizide mit nachgewiesener Wirkung gegen Sternrußtau. Netzschwefel wirkt vorbeugend und kurativ. Nicht bei Hitze über 28 °C anwenden (Verbrennungsgefahr). Wartezeiten bei Nutzpflanzen einhalten.",
      steps: [
        "Produkt nach Herstellerangabe dosieren",
        "Bei bedecktem Himmel oder am frühen Morgen sprühen",
        "Alle Blattoberflächen gleichmäßig benetzen",
        "Alle 10–14 Tage wiederholen",
        "Im Abstand von mindestens 1 Woche nach Laubentfernung anwenden",
      ],
      effort: "MEDIUM",
      durationMin: 25,
      timeframe: "THIS_WEEK",
      ecoScore: 3,
      successRate: "HIGH",
      minExperience: "INTERMEDIATE",
      safeForChildren: false,
      safeForPets: true,
      costEur: "€€",
    },
    {
      id: "m_adr_sorten",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED", "EFFECTIVE"],
      title: "ADR-Sorten wählen und Pflanzabstand einhalten",
      description:
        "Langfristig wichtigste Prävention. ADR-geprüfte Rosen zeigen nachgewiesene Resistenz gegen Sternrußtau und weitere Krankheiten. Ausreichender Pflanzabstand sorgt für Luftzirkulation und trocknet Blätter schneller ab.",
      steps: [
        "Bei Neupflanzung ausschließlich ADR-geprüfte Sorten wählen (z. B. 'Knock Out', 'Lions-Rose', 'Rote The Fairy')",
        "Mindestabstand von 60–80 cm zwischen den Rosen einhalten",
        "Standort mit guter Luftzirkulation wählen, keine Hecken-Einengung",
        "Regelmäßig auslichten, damit Blätter schneller abtrocknen",
      ],
      effort: "MEDIUM",
      durationMin: 90,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "HIGH",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
    {
      id: "m_giessen",
      type: "CULTURAL",
      style: ["ORGANIC", "BALANCED"],
      title: "Morgens gießen, nur am Boden",
      description:
        "Nasse Blätter begünstigen die Sporenkeimung erheblich. Durch Bodenguss morgens trocknen Blätter im Tagesverlauf. Oberirdische Bewässerung und Abendguss konsequent vermeiden.",
      steps: [
        "Ausschließlich am Boden gießen — Tropfschlauch oder Gießkanne direkt an der Wurzel",
        "Nur morgens gießen, damit Pflanzen bis Abend abtrocknen können",
        "Kein Beregner oder Überkopf-Beregnung",
        "Regenmulch (Rindenmulch) unter den Rosen reduziert Spritzwasser vom Boden",
      ],
      effort: "EASY",
      durationMin: 10,
      timeframe: "LONG_TERM",
      ecoScore: 5,
      successRate: "MEDIUM",
      minExperience: "BEGINNER",
      safeForChildren: true,
      safeForPets: true,
      costEur: "€",
    },
  ],
  prevention: [
    "ADR-geprüfte Rosensorten wählen — robust gegenüber Sternrußtau von Haus aus.",
    "Im Herbst konsequente Laubbeseitigung unter den Rosen (Sporenreservoir entfernen).",
    "Rindenmulch unter den Rosen jährlich erneuern.",
    "Ausgewogene Düngung — kein Stickstoff-Überschuss (macht Gewebe anfällig).",
    "Luftige Pflanzung mit mindestens 60–80 cm Abstand.",
    "Morgens gießen, Blätter so trocken wie möglich halten.",
  ],
  sources: [SOURCES.JKI, SOURCES.GPP, SOURCES.LFL],
  contentConfidence: "HIGH",
  version: CONTENT_VERSION,
  imageUrl:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Diplocarpon_rosae_on_Rosa.jpg/320px-Diplocarpon_rosae_on_Rosa.jpg",
};
